jenkinsci/workflow-cps-plugin

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

[JENKINS-34064](https://issues.jenkins-ci.org/browse/JENKINS-34064)
Until https://github.com/cloudbees/groovy-cps/pull/24 can be finished, or at least merged & released in its current state, we have to revert to the earlier release.

[JENKINS-34064] Backing out JENKINS-26481 fix

---

pom.xml

Otherwise with https://github.com/jenkinsci/jenkins/pull/2172 plugins will (correctly) be disabled due to version mismatches.
@reviewbybees

Fix test-scoped deps

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepEndNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
src/test/java/org/jenkinsci/plugins/workflow/DynamicEnvironmentExpanderTest.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java

[JENKINS-26156](https://issues.jenkins-ci.org/browse/JENKINS-26156)
Before:
* if you passed null, or simply did not call it at all, there were body block nodes contrary to documentation
* if you passed non-null, you would get an `IllegalStateException` (!)
After:
* body block nodes are created unconditionally
* you may call it, with a non-null name, if you want a label on the body block
@kohsuke seems to have been trying to elide body block nodes when they contribute no interesting information, as in most steps accepting a closure (`node`, say, as opposed to `retry` which _might_ have something interesting to show like a retry count). But this was never actually implemented, and seems too dangerous to try anyway. What if a step asked to elide the body block nodes but then actually called …

[JENKINS-26156] BodyInvoker.displayName was broken

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly

@HRMPW suggested turning on sandbox mode by default in all cases, even for Jenkins administrators. (See https://github.com/jenkinsci/pipeline-plugin/pull/67 for the original conditional logic.) There are several arguments for doing this:
* At least pending [JENKINS-28178](https://issues.jenkins-ci.org/browse/JENKINS-28178), if you want to convert to `Jenkinsfile` (whether for multibranch support, or simply to keep single-project sources in SCM) you will need to have a sandboxable script anyway, so you might as well start learning Pipeline this way.
* The sandbox will catch certain common beginner mistakes, such as
```groovy
node('slave') {
checkout …
def text = new File('something-in-workspace').text
}
```
where `readFile` was in fact needed.
@reviewbybees

Enable the sandbox by default

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition/config.jelly

@HRMPW noticed that #12 is not great in Jenkins 2.
Multibranch pipelines and organization folders are unaffected, at least until [JENKINS-33622](https://issues.jenkins-ci.org/browse/JENKINS-33622) is fixed.
@reviewbybees

[JENKINS-31831] Amendment to display a link in the config form

---

src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyClassLoaderWhitelist.java
src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java

[JENKINS-26481](https://issues.jenkins-ci.org/browse/JENKINS-26481)
Tries to improve diagnostics until https://github.com/cloudbees/groovy-cps/pull/24 can be fixed.
Before this patch, `SerializationTest.eachClosure` fails with cryptic script behavior:
```
Started
[Pipeline] node
Running on master in /tmp/junit3096297553890442745/junit8071484631883149575/workspace/demo
[Pipeline] {
[Pipeline] writeFile
[Pipeline] semaphore
[Pipeline] readFile
[Pipeline] echo
a
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
Note that there is no error in the build, it just does not run correctly. After the patch, the build fails:
```
Started
[Pipeline] node
Running on master in /tmp/junit8559386618399120809/junit4301051117364074727/workspace/demo
[Pipeline] {
[Pipeline] } …
```

[JENKINS-26481] More clearly report problem passing closures to binary methods

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globals.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globalsHelp.jelly
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/sidepanel.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

...and link to it from pipeline-syntax/index.jelly.
https://issues.jenkins-ci.org/browse/JENKINS-35395
Replaces #17 - I tried an anchor link to `pipeline-syntax/html#globalVariables` (after adding that anchor, of course) and it didn't work nicely - it always ended up focusing on a different location than it should have when rendering. So I split it out to a separate page instead.
cc @reviewbybees, esp. @jglick and @rtyler

[FIXED JENKINS-35395] Copy Global Variable docs into their own page.

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly

Like #13, displays a link to _Pipeline Syntax_ from with the _Replay_ screen, one of the places you are most likely to need it.
@reviewbybees

Show Snippetizer link also from ReplayAction

---

src/main/js/samples.js

Otherwise you get builds marked as failed due to JUnit failures, which looks crappy. With the patch:
@reviewbybees

Better Maven sample

---

src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java

Added run2() to ReplayAction which returns Queue.Item rather than
QueueTaskFuture, so that Blue Ocean can reference the item in the
queue for its REST api.
Note: I'm not sure what the best way to do this was so I added run2 rather than modifying run's return signature.
@reviewbybees

[JENKINS-36289] Added ReplayAction#run2

---

src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

[JENKINS-27421](https://issues.jenkins-ci.org/browse/JENKINS-27421)
Tried to solve using
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java b/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
index f7f6ab3..355e478 100644
--- a/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
+++ b/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
@@ -46,7 +46,11 @@ import org.jenkinsci.plugins.workflow.pickles.PickleFactory;
@Extension public class IteratorHack extends PickleFactory {
private static final Logger LOGGER = Logger.getLogger(IteratorHack.class.getName());
-    private static final Set<String> ACCEPTED_TYPES = ImmutableSet.of("java.util.ArrayList$Itr");
+ …
```

[JENKINS-27421] Test for LinkedHashMap.Entry problem

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/help.jelly

Follow-up to #28.
@reviewbybees esp. @kohsuke, @abayer

[JENKINS-29922] Describe step call formats in “Pipeline Syntax: Reference”

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java

Useful to be able to see if very large graphs are being encountered, which can have performance implications.
@reviewbybees esp. @svanoort & @fbelzunc

Include the running node count in Pipeline thread dumps in support bundles

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/dsld.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/gdsl.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

[JENKINS-29922](https://issues.jenkins-ci.org/browse/JENKINS-29922)
Means that plugins which offer `SimpleBuildStep`s or `SimpleBuildWrapper`s with `@Symbol`s will have those extensions be displayed like native steps in _Snippet Generator_:
Also solves one component of [JENKINS-37215](https://issues.jenkins-ci.org/browse/JENKINS-37215), mainly because I had to do _something_ just to make the existing content generators compile again: the static HTML reference (but not GDSL/DSLD) now shows such extensions like top-level steps:

[JENKINS-29922] Display single-argument metasteps inline in Snippetizer

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Had disabled a test due to still-undiagnosed failures on Jenkins 2, which concealed the fact that a recent bug fix (#29) regressed the leak on Jenkins 1:
```
{groovy.lang.GroovyClassLoader$InnerLoader@571df0f9=private static final org.jboss.marshalling.reflect.SerializableClassRegistry org.jboss.marshalling.reflect.SerializableClassRegistry.INSTANCE->
org.jboss.marshalling.reflect.SerializableClassRegistry@67289b2f-registry->
org.jboss.marshalling.reflect.UnlockedHashMap@46269dbf-table->
org.jboss.marshalling.reflect.UnlockedHashMap$Table@4a13d1ef-array->
[Ljava.lang.Object;@2b2b3f3-[121]->
[Lorg.jboss.marshalling.reflect.UnlockedHashMap$Item;@182e8565-[0]->
org.jboss.marshalling.reflect.UnlockedHashMap$Item@13d66b69-key->
groovy.lang.GroovyClassLoader$InnerLoader@571df0f9}
``` …

Memory leak introduced with the fix of JENKINS-36372

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

Intended to augment https://github.com/jenkinsci/script-security-plugin/pull/80 a bit: some class loading calls from deep in the bowels of Groovy use the CCL, and so we can get a performance benefit by making sure that is set to the `GroovyClassLoader`, since that will delegate to the `SandboxResolvingClassLoader` which will then cache the expensive core results.
Only partially effective, since plenty of other calls either using `Class.forName(String)`—meaning, look it up in the Jenkins core class loader, typically provided by the application server—or use the `ClassLoader` associated with some reference class, which might be in the JRE, Jenkins core (incl. Groovy itself), a plugin, or the Groovy script. Any such calls which use an initiating loader below `GroovyClassLoader`¹ will still …

Set the Thread.contextClassLoader to the GroovyClassLoader

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java

[JENKINS-37538](https://issues.jenkins-ci.org/browse/JENKINS-37538)
Amends #42. Probably fixes a bug which I have not yet been able to reproduce. My working hypothesis is that with certain class loaders as `Thread.contextClassLoader`, `SAXParserFactory.newInstance()` fails for reasons TBD but probably related to a mismatch between the `ClassLoader` defining some copy of `SAXParserFactory` and one defining a copy of `org.apache.xerces.jaxp.SAXParserFactoryImpl`, due to a design flaw in `ServiceLoader`.
My first thought was to use `d.clazz.getClassLoader()` so that the `Step`’s own plugin code would be available, but in the case of `artifactory` (cf. https://github.com/JFrogDev/jenkins-artifactory-plugin/pull/30) this will delegate to the loader of `parameterized-trigger` which currently …

[FIXED JENKINS-37538] Set the context class loader to a neutral value inside step executions

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/StateMetaStep.java

[JENKINS-37403](https://issues.jenkins-ci.org/browse/JENKINS-37403)
Downstream of https://github.com/jenkinsci/structs-plugin/pull/10
cc @reviewbybees esp @jglick

JENKINS-37403 - downstream change to use SymbolLookup.getSymbolValue(…)

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/help-script.html

You want people to go to `/job/…/pipeline-syntax/` (in a separate tab), not the plugin wiki as the original text might have been read to imply:
> Groovy script defining this Pipeline. Use the **Pipeline Groovy** link for details.
> (from [Pipeline: Groovy](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin))
@reviewbybees

Pipeline Syntax, not Pipeline Groovy

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MultiShape.java

[JENKINS-38037](https://issues.jenkins-ci.org/browse/JENKINS-38037)
Back in [this change](https://github.com/jenkinsci/workflow-cps-plugin/commit/7857e23bfc9e404063a1e512287a0a735445d318), I screwed up and used the metastep descriptor for determining whether a symbol-driven `Describable` had a single required argument. That was...wrong. It was only relevant for executable symbols, and we should be checking the `DescribableModel` for the symbol, not the meta-step. So, fixing that.
cc @reviewbybees esp @jglick @kohsuke

[FIXED JENKINS-38037] Single-arg check for executable symbols fix

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java

[JENKINS-38169](https://issues.jenkins-ci.org/browse/JENKINS-38169)
If you call `echo message:'foo'` previous to this change, the Map that
gets passed as the first element of args ends up being used as the
sole parameter itself, so you end up with `name:[name:'foo']` being
passed as the args. That's obviously wrong. So let's add a check to
see if there is a `soleArgumentKey`, the arg map only has one
key/value, and that key is equal to `soleArgumentKey` - if that's
true, just pass the arg map directly.
cc @reviewbybees esp @jglick

[FIXED JENKINS-38169] Treat single required+named param differently.

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java

I was looking at a problem where a test seemingly hangs forever. I tracked it down to a problem in CPS VM,
but what made this difficult for me is that a RuntimeException happening in some unexpected part of CPS VM went unreported.
If this error happened in the field, I would have never been able to figure this out. So I'm adding a diagnostics here to make sure
we can catch this class of problems.
Just for the record, the particular problem in CPS VM is a NullPointerException in the following place:
at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:283)
at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.launch(CpsBodyExecution.java:161)
at org.jenkinsci.plugins.workflow.cps.CpsBodyInvoker.launch(CpsBodyInvoker.java:189)
at …

Detect failure in CPS VM

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/EmperorHasNoClothes.java

Fixing a bug in CPS VM about how it handles an exception in sync body.
When the body of a step is synchronous and explodes, the failure should be recorded and the pipeline job should move on.
But instead, this hangs because `CpsBodyExecution` has a bug in how it handles this case. It tries to launch the body  in a separate CPS thread, and puts the parent CPS thread on hold. Yet when the child CPS thread ends with an exception, it fails to record this result correctly, and it gets into the eternal sleep in which the parent CPS thread expects to be notified of the outcome of the child CPS thread, which never arrives.
Any exception aside from `CpsCallableInvocation` is a sign that the execution has completed abnormally and synchronously. So this code pass should have close parallel to the …

Incorrect handling of synchronous abnormal termination of the body block

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadTest.java

@cyrille-leclerc [encountered a case](https://gist.githubusercontent.com/jglick/b906ae79a0dd857dae0098453fe03612/raw/fe90a36ee9311e35f0ad451c4d4e823642486da2/gistfile1.txt) where `StepExecution.stop` was called but threw an exception; the build kept running. Normally `DurableTaskStep.Execution.stop` first checks whether the remoting channel is alive and well, but in this case for some reason that check passed yet an actual attempt to use the channel to run a termination command failed. Best to abandon the step as a failure at that point.
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/8 for nicer reporting.
@reviewbybees

When StepExecution.stop throws an exception, forcibly kill the step and record both stack traces

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globals.groovy

This allows links to specific variables like this: `/pipeline-syntax/globals#env`

Add anchors for variables

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsWhitelist.java
src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
src/main/java/org/jenkinsci/plugins/workflow/cps/ParamsVariable.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/ParamsVariable/help.jelly
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/ParamsVariableTest.java

Implements [JENKINS-27295](https://issues.jenkins-ci.org/browse/JENKINS-27295) and [JENKINS-29952](https://issues.jenkins-ci.org/browse/JENKINS-29952) and also demonstrates that [JENKINS-28447](https://issues.jenkins-ci.org/browse/JENKINS-28447) is fixed by the upstream https://github.com/jenkinsci/workflow-job-plugin/pull/24.
@reviewbybees

[JENKINS-27295] [JENKINS-29952] Overhaul of access to build parameters

---

src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java

Trying to solve/diagnose some test flakes noticed in recent release tests.
```
java.lang.NullPointerException
at org.jenkinsci.plugins.workflow.SerializationTest$1.evaluate(SerializationTest.java:52)
java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method)
at org.jvnet.hudson.test.JenkinsRule.waitForCompletion(JenkinsRule.java:1231)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecutionTest$7.evaluate(CpsFlowExecutionTest.java:262)
java.lang.NullPointerException
at org.jenkinsci.plugins.workflow.cps.CpsThreadDumpTest.simple(CpsThreadDumpTest.java:47)
```
@reviewbybees

Some flaky tests

---

src/main/java/org/jenkinsci/plugins/workflow/cps/ParamsVariable.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/ParamsVariable/help.jelly

Saw some people on #jenkins trying to mutate it: [JENKINS-38739](https://issues.jenkins-ci.org/browse/JENKINS-38739) for example.
@reviewbybees

Clarify and enforce that params is read-only

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

Someone on #jenkins claimed to have been using some idiom along the lines of
```groovy
if (SOME_BUILD_PARAM_NAME == '') {
SOME_BUILD_PARAM_NAME = 'fallback'
}
useSomehow(SOME_BUILD_PARAM_NAME)
```
which I had never intended to support but apparently worked prior to #60 ([release notes](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin#PipelineGroovyPlugin-2.18%28Sep23%2C2016%29)). It seems that the `GlobalVariable` and `env` fallbacks were taking precedence over `Binding`s, which is probably unwanted—generally we want to let scripts override symbols. This should restore the previous behavior in that case.
@reviewbybees

Delegate preferentially to global bindings before applying custom getProperty behaviors

---

pom.xml

IIUC this will ensure that anyone upgrading from [2.17 or earlier](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin) is asked to read release notes according to [this system](https://wiki.jenkins-ci.org/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions).
@reviewbybees esp. @daniel-beck who suggested it

compatibleSinceVersion=2.18

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java

[JENKINS-34637](https://issues.jenkins-ci.org/browse/JENKINS-34637)
Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/20.

[JENKINS-34637] Failure to kill bodies from timeout

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

[JENKINS-27421](https://issues.jenkins-ci.org/browse/JENKINS-27421)
Downstream of https://github.com/jenkinsci/script-security-plugin/pull/92.
@reviewbybees

[JENKINS-27421] Improve behavior of map iteration workaround a bit

---

pom.xml

[JENKINS-39154](https://issues.jenkins-ci.org/browse/JENKINS-39154)
Rejects https://github.com/jenkinsci/plugin-pom/pull/36 until I can get an explanation from @tfennelly on how this plugin should be updated.
@reviewbybees ASAP

[JENKINS-39154] Restore ACE editor

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java

Should reduce memory footprint for Jenkins pipeline a bit and simplify garbage collection some. 
See [JENKINS-39456](https://issues.jenkins-ci.org/browse/JENKINS-39456)

Intern or deduplicate many duplicated strings

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Regression in #41. Corrects a `NullPointerException` thrown at the end of a very old build noticed in tests after https://github.com/jenkinsci/pipeline-input-step-plugin/pull/9.
@reviewbybees

scripts might be null if loading old builds

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepDescriptorCache.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java

Profiling showed this is rather expensive, due to repeated iteration needs to find the descriptor. 
This converts this to a simple, fast hashmap lookup, rather than checking against a whole list of items. 
Side point: it probably reduces the garbage objects Jenkins generates.

Cache the StepDescriptors to elliminate a moderate bottleneck

---

src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java

If the test in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/24 is run against `workflow-cps` 2.22, as it is currently, there is a `NullPointerException` which is harmless—corrected in #89. But if it is run against 2.23 to fix that, we get an exception deserializing flow nodes, introduced by code in #82. I am not exactly sure what the problem is, since with this patch the flow nodes do wind up correctly deserialized, and the `*.xml` is correct; somehow at the time `readResolve` is called, all fields are null.
@reviewbybees esp. @svanoort

[JENKINS-40909] NPE encountered during tests

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Reverts this aspect of behavior to that prior to #46, which should avoid the incompatibility noted in [2.14](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin#PipelineGroovyPlugin-2.14%28Sep07%2C2016%29). Script authors should still of course avoid using unserializable local variables.
Also avoids some load spent saving `program.dat` unnecessarily, though in my tests so far the benefit is typically negligible: while roughly half of the program saves are avoided, each one only took a few milliseconds anyway. Could affect certain scripts more, if they do a lot of (CPS-transformed) Groovy in between steps.
@reviewbybees

Avoid saving program.dat if we are about to run another chunk anyway

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNode.java

Allows compatibility while permitting workflow-api to expose step info. 
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/28
@reviewbybees

Make StepNode just extend higher-level API in workflow-api

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java

Begins to address [JENKINS-32986](https://issues.jenkins-ci.org/browse/JENKINS-32986). Does not go so far as to impose a hard limit. #93 probably required for any sort of quota.
Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/29.
@reviewbybees

[JENKINS-32986] Apply a timeout to some hang-prone operations in the CPS VM thread

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

[JENKINS-42189](https://issues.jenkins-ci.org/browse/JENKINS-42189)
Directly solves the soft leak, and probably also solves the deadlock (without waiting for https://github.com/apache/groovy/pull/489 in a 2.4.9 update) by simply skipping the affected code path.
Amends #83. Required by https://github.com/apache/groovy/pull/219 and https://github.com/apache/groovy/pull/427.
@reviewbybees

[JENKINS-42189] Fix ClassInfo cleanup in Groovy 2.4.8+

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

[JENKINS-42189](https://issues.jenkins-ci.org/browse/JENKINS-42189)
@reviewbybees

[JENKINS-42189] Forcing a test failure in case of another soft leak

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition/help-scriptPath.html

A user was seen trying to use `\` with `GitSCM` and it did not work.
@reviewbybees

Noting that CpsScmFlowDefinition.scriptPath must use `/` as the separator

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Just noticed this file was being left behind after the build completes, when it is no longer needed and is just a waste of disk space.
(Not deleting from `croak`, when we leave it behind for possible analysis.)
@reviewbybees

Delete program.dat at the end of a build

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionValidatorTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Useful for determining, both during experimentation and in the field, where the most load is consumed by the Jenkins master when running Pipeline builds: class loading for Groovy compilation, saving `program.dat`, etc.
Supersedes the simple logging in #92.
@reviewbybees

Record timing information for internal processes

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java

[JENKINS-43934](https://issues.jenkins-ci.org/browse/JENKINS-43934)
Never really posed a problem before, probably because there is no existing `StepDescriptor.newInstance` override which would be expecting evaluated `String`s in a collection type, but the previous behavior was at least potentially wrong…and this is needed for https://github.com/jenkinsci/workflow-cps-plugin/pull/98 so we might as well do it anyway.
`DescribableModel` already has `GString` handling, which really should never have been there, but we cannot remove that compatibly.
@reviewbybees

[JENKINS-43934] Flatten GString’s found in step arguments, even when present in nested collections

---

src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepDescriptorCache.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepDescriptorCacheTest.java

[JENKINS-44406](https://issues.jenkins-ci.org/browse/JENKINS-44406)
Don't rely on Memoizer to handle nulls correctly - it doesn't handle a computed null because ConcurrentHashMap can't (potential fix to Jenkins core).

Fix StepDescriptorCache handling of null StepDescriptor lookup [JENKINS-44406]

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java

Corrects a regression in #93, caught only by a test in `workflow-cps-global-lib`—I suppose something about the existence of a trusted loader in the hierarchy triggers the problem.
Subsumes #135.
@reviewbybees

TimingLoader leak

---

pom.xml

Introduced in #98.
@reviewbybees

InjectedTest failure

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/EchoResultStep.java

[JENKINS-34464](https://issues.jenkins-ci.org/browse/JENKINS-34464)
Downstream of https://github.com/jenkinsci/structs-plugin/pull/19, upstream of https://github.com/jenkinsci/workflow-multibranch-plugin/pull/63
The `workflow-multibranch` test was failing, seemingly due to `workflow-cps` having the older `structs` version (plus some other problems, but those are fixed over in that PR anyway). So let's bump the `structs` release.

[JENKINS-34464] Bump structs version, add test for result roundtrip

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

Since you cannot override the contextual `FlowNode` with `BodyInvoker` as a contextual variable, there is no need to look up the `CpsThread`, which is a blocking operation. Would have helped avoid a problem in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/2 and might have even helped https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/50 which was a showstopper. (`CpsStepContext.getNode` is also potentially blocking, but at a lower level—does not need the program to have resumed AFAIK.)
@reviewbybees

A call to get(FlowNode) need not wait for the CpsThread

---

README.md

Removing iterator/DGM-related caveats from README

---

src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java

Amends #148 to address the first bullet point of [JENKINS-45101](https://issues.jenkins-ci.org/browse/JENKINS-45101), which it turns out is not the fault of Blue Ocean, and can in fact be seen in the original **Pipeline Steps** view as well.
@reviewbybees

[JENKINS-45109] Also adjust StepNode.getTypeDisplayName to handle metasteps

---

Jenkinsfile

The [JENKINS-33358](https://issues.jenkins-ci.org/browse/JENKINS-33358) Groovy update went into 2.47. So at first I planned to have CI test
* the current plugin baseline (2.7.3)
* 2.46.3, the last LTS prior to that update, and after the change in 2.12 (IIRC) which enforced plugin dependencies at startup
* 2.60.1, the current LTS, after that update
But then I decided to skip 2.46.x since it uses the same Groovy 2.4.7 as the baseline (unlike the case in, say, `workflow-cps-global-lib` which still needs to test against three lines—using Groovy 1.x, 2.4.7, and 2.4.8), and has the same plugin dependency enforcements as the current LTS. And saving some machine time for a heavily-edited plugin is probably not a bad idea anyway.
@reviewbybees

Adjusting Jenkins versions being tested

---

pom.xml

Consumes more than ⅔ of the size of `workflow-cps.hpi`, and is unused since we pick it up from the Jenkins core classpath anyway.
@reviewbybees

Stop bundling guava.jar

---

src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java

Cf. https://github.com/jenkinsci/workflow-step-api-plugin/pull/27.
@reviewbybees

The argumentsToString parameter was not, in fact, checked for null

---

src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java

[JENKINS-44548](https://issues.jenkins-ci.org/browse/JENKINS-44548)
`CpsFlowExecution.storage` and `startNodes` are initialized after `onLoad` by `initializeStorage`. But `flowStartNodeActions`, normally initialized from the constructor, will not be reinitialized after a load from disk, so this could be null in case we are in `loadProgramFailed`.
@reviewbybees

[JENKINS-44548] NPE from loadProgramFailed

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

The error in [JENKINS-46191](https://issues.jenkins-ci.org/browse/JENKINS-46191), for example, can apparently be fatal during startup:
```
BUG! exception in phase 'class generation' in source unit 'WorkflowScript' Error while popping argument from operand stack tracker in class WorkflowScript method …. 
at org.codehaus.groovy.classgen.asm.OperandStack.popWithMessage(OperandStack.java:72) 
at …
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558) 
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298) 
at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268) 
at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688) 
at groovy.lang.GroovyShell.parse(GroovyShell.java:700) 
at …
```

Catch any kind of exception from parseScript

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-46391](https://issues.jenkins-ci.org/browse/JENKINS-46391)
Downstream of https://github.com/jenkinsci/script-security-plugin/pull/146

[JENKINS-46391] Test verifying CPS-specific ~/foo/ behavior

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Observed in a build on a server where agents are ephemeral, after restarting Jenkins and then killing a resumed build:
```
Resuming build at … after Jenkins restart
Waiting to resume part of … #…: ???
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next available executor
Waiting to resume part of … #…: Waiting for next …
```

CpsThreadGroup.scripts could be empty in readResolve

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java

No semantic change, just makes it easier to experiment with targeting 2.60+ cores.
@reviewbybees

Make DSL compilable under -source 8 with some versions of javac

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Seems sane, putting up for review
> 2017-10-18 23:35:16.916+0000 [id=731]	WARNING	o.j.p.w.cps.CpsVmExecutorService#reportProblem: Unexpected exception in CPS VM thread: CpsFlowExecution[Owner[BUILDNAME]]
java.lang.NullPointerException
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getFirstHead(CpsFlowExecution.java:1184)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onProgramEnd(CpsFlowExecution.java:1032)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:351)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
at …

Add some more null-proofing for CpsFlowExecution.heads

---

src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

[JENKINS-47339](https://issues.jenkins-ci.org/browse/JENKINS-47339)
Allows rebuilding a Pipeline run with the exact same script.
This will be used directly by Blue Ocean for its rebuild functionality, which doesn't need to be able to make changes to the script, so shouldn't require `Item.CONFIGURE` or `ReplayAction.REPLAY`. Instead, it'll require either `Item.BUILD` or `ReplayAction.REBUILD`.
cc @reviewbybees @i386

[FIXED JENKINS-47339] Add build-implied REBUILD permission.

---

src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayPipelineCommand.java

Small consistency improvement: remove then also getName() override to rely on default class name to CLI command name conversion.
(which will stay "replay-pipeline").
I have come across this trying to assess how often people were overriding getName() and apparently this is the only occurrence.
As I think there's no reason anyone would inherit/depend on this, I guess we can safely just rename it for consistency.
(Good thing being when crawling codebase, one will be able to translate the command name into a probable class name, and find it right away using the type-search feature of one's IDE).
@reviewbybees esp. @jglick

Rename ReplayCommand into ReplayPipelineCommand

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

Pulls in and properly tests https://github.com/cloudbees/groovy-cps/pull/77 -- this is to verify that we're correctly killing bits running on an Executor if the pipeline dies due to excessive  nesting of groovy-cps functions/closures.
Yes, it's a snapshot dep. Yes, it requires building the downstream PR to get it to run correctly because of the special-snowflake nature of the groovy-cps library.  I'm sorry.

Verify fixes to limit unlimited pipeline recursion

---

src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
src/test/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHackTest.java

[JENKINS-46597](https://issues.jenkins-ci.org/browse/JENKINS-46597)
For whatever reason that I can't exactly determine yet, Groovy
categories seem to, at least in some scenarios, treat `Map` differently
than `SortedMap`. I know, weird. Anyway, `IteratorHack#entrySet(Map)`
and friends would fire for `HashMap` but not for `TreeMap`. Adding
these shim methods fixes `entrySet`, `keySet`, and `values`.
Replaces https://github.com/jenkinsci/workflow-scm-step-plugin/pull/23

[FIXED JENKINS-46597] IteratorHack needs to special-case SortedMap

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/ParamsVariable/help.jelly

Follows up https://github.com/jenkinsci/script-security-plugin/pull/153.
@reviewbybees

Note the existence of Map.get(Object, Object) which is useful for params

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

Fix for [JENKINS-48644](https://issues.jenkins-ci.org/browse/JENKINS-48644)

Test and fix for missing ArgumentsAction string inside a stage

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

Picks up both https://github.com/jenkinsci/structs-plugin/pull/31 and https://github.com/jenkinsci/structs-plugin/pull/30  plus the unreleased https://github.com/jenkinsci/structs-plugin/pull/29 (until released).
Used to ensure it doesn't violate workflow-cps tests and picks up new APIs correctly.

Pick up structs improvements and adapt to use preferred APIs

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
src/test/resources/org/jenkinsci/plugins/workflow/cps/steps/localMethodCallWithinLotsOfBranches.groovy

Removes yet another cause of needless runtime Reflection/classloading when running pipeline.  Should result in running steps much faster generally and with less disk hits from classloading + less lock contention.
Similar to https://github.com/jenkinsci/structs-plugin/pull/31 but on the DSL side (using the DescribableModel more efficiently with what is provided) -- also related to https://github.com/jenkinsci/structs-plugin/pull/30. 
Incidentally includes https://github.com/jenkinsci/workflow-cps-plugin/pull/201 for the fixed Structs.
Justification: see attached image showing Object monitor thread contention when running 40x concurrent trivial pipelines -- this is one of the top 10 leading bottlenecks.
**Remaining locking bottlenecks for future PRs:**
* Script Security - …

Optimize fetching the sole parameter to avoid needless reflection and possible classloading

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java

Specifically, I'm going to be consuming this in Declarative for a
Declarative-specific "directive generator" like the Snippet Generator,
but for Declarative directives like `options`, `triggers`, `when`, etc.
There'll eventually be a followup PR once that has been implemented in
Declarative to add a link to the Directive Generator or whatever we
end up calling it to the Pipeline Syntax sidepanel.jelly
(conditionally - i.e., if a new enough version of Declarative is
installed) but there's no point in doing that yet since I can't
actually implement it without this method being public. =)

Add new public object2Groovy method for use in other contexts.

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

Fixes [JENKINS-49961](https://issues.jenkins-ci.org/browse/JENKINS-49961) and includes test for same.
Save is not needed *here* when flag is mutated because it will be re-evaluated at onLoad.  Besides, the run will probably be saved momentarily due the results of resuming the build.
@reviewbybees

Fix [JENKINS-49961] by avoiding an unsafe save operation when toggling ResumeEnabled if the FlowExecutionOwner is not yet set

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/sidepanel.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

This will allow Declarative to contribute its own links to the sidepanel as well.
Upstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/250

Switch Snippetizer sidepanel links to use an extension point

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

The main fixes are here https://github.com/jenkinsci/workflow-job-plugin/pull/93 but this helps harden against the following and adds a bunch of diagnostic logging:
* [JENKINS-50199](https://issues.jenkins-ci.org/browse/JENKINS-50199)
* [JENKINS-46986](https://issues.jenkins-ci.org/browse/JENKINS-46986)
* [JENKINS-50407](https://issues.jenkins-ci.org/browse/JENKINS-50407)
It also subsumes: https://github.com/jenkinsci/workflow-cps-plugin/pull/215

Fix a whole wad of Resume issues and add a bunch of diagnostic logging for FlowHead problems etc

---

pom.xml

It got mangled due to a glitch in the Maven release, sigh.

Fix Maven release bugginess once more

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

... before they can cause catastrophic issues.  
Solution for [JENKINS-50752](https://issues.jenkins-ci.org/browse/JENKINS-50752) which is causing problems in the wild. 
Upstream is: https://github.com/jenkinsci/workflow-api-plugin/pull/68

Bulletproof against [JENKINS-50752] by catching unserializable step arguments

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java

Method calls made in a pipeline get routed to CpsScript's invokeMethod before being executed.  
**Currently**:
The method checks to see if the method in question has been defined as a GlobalVariable and if not - checks the DSL where if not present, an error will be thrown. 
Given this flow - there is no room for user defined closures injected into the script binding to get executed in the pipeline. 
**Fix**:  
Check the script binding for variables named the same as the method name attempting to be invoked.  If the variable exists and it is of type CpsClosure2, execute the closure and pass in the arguments.  
User defined closures should take precedence over library methods or pipeline DSL steps as they were defined in the most local context to the script execution. 
**Reproduce:**
~~~ …

Edge Case: CpsScript invokeMethod does not execute closures defined in the script binding

---

src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/EchoStringAndDoubleStep.java

Newer versions of junit plugin have `junit` as an actual `Step`, so
anything expecting a metastep when using `junit` will not get a
metastep. So, let's stop using `junit` in tests in general. This is
relevant now in the PCT, will be relevant eventually when we bump the
junit dependency here as well.

Stop using junit in metastep tests

---

doc/persistence.md
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/PersistanceController.java
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

Addresses the following root causes of problems in Pipeline persistence/durability:
* Pipelines which modify the heads in an execution *without* ensuring the corresponding FlowNodes are also saved to disk - this will cause issues when trying to load the execution -- applies only to the fully durable modes (since non-durable just won't persist period)
* Pipelines which modify the `CPSThread.head` `FlowHead` and its `FlowNode` without ensuring the CpsFlowExecution is saved (via `saveOwner()` that saves the `WorkflowRun`).  This causes an NPE loading the program, because the FlowHead may map to a head in the CpsFlowExecution that will not exist at time of deserialization. 
* Provides some documentation on the persistence model so others do not endure my pain
* Removes explicit persistence …

Fix more subtle durability issues 

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

[JENKINS-50888](https://issues.jenkins-ci.org/browse/JENKINS-50888)
We missed the case of someone immediately modifying the build and saving before we onLoad could get invoked.

Fix and test for JENKINS-50888 by supporting serialization of execution before onLoad was called

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

A deadlock can arise if multiple threads tries to access storage
simultaneously while one of them doing it from a synchronized
method. The cause is that timing operation also tries to get the
instance lock from inside the storage r/w lock.
Solution is to change the order of locking by having the timing
object wrapping the call to the r/w storage lock instead of the
opposite.

JENKINS-51123: Fix deadlock in CpsFlowExecution

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

See [deadlock file](https://issues.jenkins-ci.org/secure/attachment/42497/deadlock.txt) from [JENKINS-51132 comment](https://issues.jenkins-ci.org/browse/JENKINS-51132?focusedCommentId=337105&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-337105). 
This prevents deadlocks by ensuring we do not lock Execution before Run (usually by separating the synchronization scopes). 
Lock order should always be Run -> Execution when locks are nested, or locks should be separated (the approach generally used here).
Why aren't there testcases?   I have low confidence in our ability produce a testcase that replicates all these deadlocks.

Fix more deadlocks

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java

Subsumes #230 and amends a mistake in #220: use of a beta API from the version of Guava currently bundled in Jenkins core, which has [subsequently been deleted](https://google.github.io/guava/releases/14.0/api/docs/com/google/common/io/NullOutputStream.html), causing mayhem if you try to run Pipeline-based tests with a newer Guava in the test classpath.
From [this search](https://github.com/search?q=user%3Ajenkinsci+%22com.google.common.io.NullOutputStream%22&type=Code) this seems to be the only usage in non-test code of this class except for `openshift-deployer` which has not been touched in three years.

Do not use com.google.common.io.NullOutputStream

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

`done` used to be a boxed `Boolean`, but it was changed to a primitive in e69a24c, so the annotation and comment are obsolete.

Remove obsolete annotation and comment

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/AmbiguousEchoLowerStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/AmbiguousEchoUpperStep.java

See [JENKINS-53333](https://issues.jenkins-ci.org/browse/JENKINS-53333).
This PR allows Pipeline steps to be specified using the full class name, in case multiple steps exist in the Jenkins instance with the same function name.
For example, this PR allows the following:
'org.jenkinsci.plugins.workflow.steps.EchoStep'('Hello, world!')
'org.jenkinsci.plugins.workflow.steps.EchoStep' 'Hello, world!'
steps.'org.jenkinsci.plugins.workflow.steps.EchoStep'('Hello, world!')
// all are equivalent to:
echo 'Hello, world!'
The syntax is weird to say the least, but the following already works today (Verified in `DSLTest#quotedStep`, maybe just Groovy weirdness), so it is at least consistent on that front:
'echo' 'Hello, world!' // Quotes around echo?!
steps.'echo' 'Hello, world!'
@jglick suggested …

[JENKINS-53333] Allow steps to be invoked using their full class name

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/Messages_zh_CN.properties

Removed the unnecessary / invalid Dollar sign in the English property file.
Also removed the additional space as it is a bit of unnecessary change and may break some tools working with the API.
These two things were introduced with #235.

Fixed i18n properties

---

src/main/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSet.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java

See [JENKINS-53079](https://issues.jenkins-ci.org/browse/JENKINS-53709).
Despite being annotated with `@PersistIn(NONE)`, `ContextVariableSet`s appear to have been persisted as part of `CpsThread` since at least 2014. Marking that field transient produces a ton of test failures, so I am assuming that the annotation was just incorrect and that it is actually ok and intentional that they be serialized as part of the program.
However, the context variables need to be cleared after a `CpsBodyExecution` completes, or else the variables will still be persisted along with the CpsThread even if it is executing unrelated code. In particular, this persistence causes issues when the context variables include an executor, as `ExecutorPickle` will attempt to rehydrate the executor upon deserialization …

[JENKINS-53709] Pop context variables after CpsBodyExecution completes

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsCompilationErrorsException.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepTest.java

See [JENKINS-40109](https://issues.jenkins-ci.org/browse/JENKINS-40109).
This PR makes compilation errors thrown by `LoadStep` serializable, and exposes an exception that is reused to fix similar errors when loading shared libraries in jenkinsci/workflow-cps-global-lib-plugin#54
@reviewbybees

[JENKINS-40109] Make compilation errors serializable

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java

Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/75. Extracted from #252 as an independently releasable fix necessary to avoid regressing `StepNodeTest` (specifically, proper display of metasteps in the classic UI console) after changes in JEP-210. Specifically, as of https://github.com/jenkinsci/workflow-job-plugin/pull/27#discussion_r222405174 `FlowNode.getDisplayFunctionName` is called from within a synchronous listener. (Formerly this was an asynchronous listener, which sounds wrong but then again `copyLogs` was asynchronous too so who cared?) And this method call pays attention to `ArgumentsAction` to display, for example, `archiveArtifacts` rather than `step` (the generic function name of `CoreStep`). So we need to ensure that at least this basic metadata …

Making sure ArgumentsAction is attached in time for GraphListener.Synchronous notification

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

See https://github.com/jenkinsci/structs-plugin/pull/42. Adjusts tests from #252 to handle a new core, whether using `structs` 1.15, 1.16, or upcoming 1.17.

[JENKINS-53917] DescribableModel again treating ChoiceParameterDefinition.choices as an object

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

See [JENKINS-55424](https://issues.jenkins-ci.org/browse/JENKINS-55424?jql=project%20%3D%20JENKINS%20AND%20assignee%20in%20(sagarailani)).
**Proposed Changelog entries**
- `Internal:` Trimmed Spaces from scriptPath String in the constructor.
**Submitter Checklist**
- ~~Appropriate autotests or explanation to why this change has no tests~~
- ~~For dependency updates: links to external changelogs and, if possible, full diffs~~
**Desired Reviewers**
@jglick 
@abayer

JENKINS-55424 - Putting a space at the end of Script Path causes java.io.FileNotFoundException

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/DynamicEnvironmentExpanderTest.java

Support the new StepEnvironmentContributor hook introduced in
jenkinsci/workflow-step-api-plugin#36.
This depends on jenkinsci/workflow-step-api-plugin#36.
The dependency version number used depends on the incrementalifyiation (JEP 305).
If requested I can perform this and submit another PR.

[JENKINS-51170] Enable the usage of the StepEnvironmentContributor extensionpoint

---

src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

[JENKINS-52189](https://issues.jenkins-ci.org/browse/JENKINS-52189)
We might consider initializing the CpsThreadGroup before the FlowStartNode (in CpsFlowExecution) to make this more "correct" but I'm a bit concerned that might have unintended consequences.

[JENKINS-52189] Ensure GraphListeners are notified of the FlowStartNode too

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/ParamsVariable/help.jelly

Groovy Map.get(Object, Object) tries to modify the Map.
Using getOrDefault() instead avoids modifying the Map.

[JENKINS-56688] Recommend Map.getOrDefault() over Map.get()

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Apparently ci.jenkins.io was logging a ton of noise of the form
```
org.jenkinsci.plugins.workflow.cps.CpsFlowExecution blocksRestart
WARNING: Not blocking restart due to problem checking running steps in CpsFlowExecution[Owner[…]]
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.util.ExecutorServiceUtils$FatalRejectedExecutionException: Cannot execute the command java.util.concurrent.FutureTask@…. The executor service is shutting down
at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:289)
at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:262)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:91)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.blocksRestart(CpsFlowExecution.ja …
```

Avoid logging RejectedExecutionException from blocksRestart

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpActionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java

[JENKINS-41791](https://issues.jenkins-ci.org/browse/JENKINS-41791)
Have you ever wondered what, exactly, is inside `program.dat`? Well I have. Alas, it is in a binary format used by a relatively obscure serialization framework, and I have never managed to write a translator to a human-readable format. So this `threadDump/program.xml` instead lets you use XStream to see the same information on a running program. You will be **shocked** at what you find after running `parallel` if you do not have this fix. Amends #245 & #83.

[JENKINS-41791] Leaked closures from parallel & load steps

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages_zh_CN.properties
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuableTest.java

[JENKINS-34973](https://issues.jenkins-ci.org/browse/JENKINS-34973): `ScriptApproval.accessRejected` not being called reliably. Downstream of https://github.com/jenkinsci/script-security-plugin/pull/243.

[JENKINS-34973] RejectedAccessException recorded more reliably

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

While reproducing JENKINS-43802 I happened to have a build which had failed during library checkout, prior to the program starting, and noticed in the log:
```
… com.cloudbees.jenkins.support.SupportPlugin writeBundle
WARNING: Could not attach ''nodes/master/pipeline-timings.txt'' to support bundle
java.io.IOException: …/…/master #1 did not yet start
at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:928)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$PipelineTimings$1.writeTo(CpsFlowExecution.java:1904)
```
This should not break generation of the entire bundle entry, but merely print a note for that build.

More graceful handling in PipelineTimings on incomplete/broken builds

---

src/main/js/samples.js

For a variety of reasons it is poor form to use Groovy interpolation in the arguments to `sh` etc. steps. Better to pass in environment variables and expand those in the host shell.
Tested on both Linux and Windows 10 using a Maven installation located in a directory with a space in the name, to exercise the quoting logic a bit.

Avoid Groovy interpolation in samples

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java

In #211 CI was sometimes getting
```
java.lang.AssertionError: expected:<[WorkflowScript.helper(WorkflowScript:2), WorkflowScript.run(WorkflowScript:3)]> but was:<[DSL.sleep(sleeping for another 0.99 sec), WorkflowScript.helper(WorkflowScript:2), WorkflowScript.run(WorkflowScript:3)]>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDumpTest.assertStackTrace(CpsThreadDumpTest.java:140)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDumpTest.nativeMethods(CpsThreadDumpTest.java:132)
```
and I saw some similar local failures. I think this should solve it. I cannot now recall why I thought the `sleep` was …

Test flake

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

See [JENKINS-56890](https://issues.jenkins-ci.org/browse/JENKINS-56890). Subsumes #287 (CC @wdforson).
Assuming that the issue has to do with reading from the map while it is being updated, this PR makes `CpsThreadGroup.thread` private and wraps it using `Collections.unmodifiableNavigableMap` to synchronize reads and writes (if the issue is instead a timing issue and the value is not yet in the map when the lookup occurs then this wouldn't help, but that seems less likely to me). All existing mutation occurs only on the CPS VM thread, so I think that as long as all iteration and read accesses that happen off of the CPS VM thread are synchronized we are safe. I was not able to reproduce the reported issue in a test, but here is the basis of what I was using to try to reproduce the issue: …

[JENKINS-56890] Make access to CpsThreadGroup.threads thread-safe

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

since TreeMap is NOT a synchronized collection (as called out, rather loudly, in [the TreeMap documentation](https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html)).
see: https://issues.jenkins-ci.org/browse/JENKINS-56890
NOTE: I have not tested this change (as I have no experience whatsoever with Jenkins development) and, as such, do not claim that it fixes the issue mentioned above.
However, `threads` _is_ currently being manipulated in a non-threadsafe manner in `CpsThreadGroup.java`, and though this change alone does not exhaustively address that (as iteration over the collection's views is still being performed without explicit synchronization ([for example](https://github.com/wdforson/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThrea …

[JENKINS-56890] CpsThreadGroup: use synchronizedNavigableMap

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSet.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSetTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/DynamicContextTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/42.

[JENKINS-41854] Interpret DynamicContext

---

src/main/java/org/jenkinsci/plugins/workflow/cps/ParamsVariable.java

Cleans up a bit of reflection introduced in #60 that has not been necessary for a while.

ParametersAction.getAllParameters can now be called directly

---

src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

Failed when updating to https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/83, since `catchError` is no longer marked `advanced`.

SnippetizerTest.generateSnippetAdvancedDeprecated failed in PCT

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

Test-only for https://github.com/jenkinsci/script-security-plugin/pull/160

Run workflow cps with Caffeine cache and unignore related tests

---

src/main/java/org/jenkinsci/plugins/workflow/cps/AbstractMismatchWhitelist.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

As described in [JENKINS-58501](https://issues.jenkins-ci.org/browse/JENKINS-58501), the [Templating Engine Plugin](https://plugins.jenkins.io/templating-engine) utilizes metaprogramming techniques to control program flow. 
The introduction of logging CPS mismatches has flooded the console log with false positive warnings that come about from how the plugin executes pipeline code. 
Rather than try to handle every edge case that may throw a false positive for the CPS mismatch warning logs, I think it would be a good approach to add a ``AbstractMismatchWhitelist`` extension that allows plugins to register their own edge cases that should prevent the log from being printed. 
Tests have been added that confirm the warning log is printed for cases not caught by a registered extension of the …

[JENKINS-58501] Add whitelist for exotic cases throwing CPS mismatch warning logs 

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

Adds two more tests for false positives, one for [JENKINS-58407](https://issues.jenkins-ci.org/browse/JENKINS-58407) and one for https://groups.google.com/d/msg/jenkinsci-users/2m5JGYJfYRs/t1hRV-rhFAAJ.
I don't really have any good ideas of how we could fix these cases without also introducing a bunch of false negatives. I think any serious fix would require recreating a good amount of Groovy's method dispatch logic so that we could figure out what `object.x()` is doing behind the scenes (For example, in the first new test case it ends up being something like `(object.x)()`, and in the second case it is something like `(object.get('x'))()`).

Add more tests for CPS mismatch warning false positives

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java

Passing `FlowExecution`'s `TaskListener` down to `DescribableModel.instantiate` to allow pipeline visibility of stray parameter warnings.
These changes rely on the following `structs-plugin` changes: https://github.com/jenkinsci/structs-plugin/pull/49

[JENKINS-33217] Pass TaskListener to DescribableModel

---

Jenkinsfile

Trying to fix the build failures we've been seeing in PRs like #311 and #307. If this helps, we might want to go ahead and switch other Pipeline plugins as well.

Use ACI agents to avoid disk space issues in CI builds

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

See [JENKINS-58501](https://issues.jenkins-ci.org/browse/JENKINS-58501).
Picks up https://github.com/cloudbees/groovy-cps/pull/99 from @steven-terrana to suppress the mismatch warnings for some kinds of metaprogramming that confuse the mismatch detection code.

[JENKINS-58501] Update to groovy-cps 1.30

---

src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java

See https://github.com/jenkinsci/workflow-job-plugin/pull/140.

[JENKINS-59083] Do not try to open the listener for a completed build

---

src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

An investigation into a memory leak revealed that in some cases, `ArgumentsActionImpl` could store references to objects defined in the Pipeline script, preventing the class loader for the Pipeline from being garbage collected.
I also fixed a subtle bug while I was here that prevented some kinds of enums from being stored at all, although maybe it would be better to keep that behavior the same as before?

Do not store enums defined in Pipeline scripts in ArgumentsActionImpl

---

src/main/js/samples.js

[JENKINS-42471](https://issues.jenkins-ci.org/browse/JENKINS-42471)
I kept the `GitHub + Maven` Scripted example as well but renamed it `Scripted Pipeline`.

[FIXED JENKINS-42471] Switch to Declarative in samples

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

See [JENKINS-58620](https://issues.jenkins-ci.org/browse/JENKINS-58620).
CpsGroovyShell test required never version of groovy-cps plugin
Please do not merge until cloudbees/groovy-cps#101 will be accepted and new groovy-cps will be released.

 JENKINS-58620 Test for the GroovyShell.evaluate mismatch ignore

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

No actual fixes here, just regression tests for the fix in script-security 1.63.
Maybe useful to try to create something similar to `SandboxInterceptorTest` from script-security here to make these kinds of tests less expensive.

Add regression tests for SECURITY-1538

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java

See [JENKINS-58878](https://issues.jenkins-ci.org/browse/JENKINS-58878) and https://github.com/jenkinsci/workflow-step-api-plugin/pull/49.
The problem AIUI was that `CpsBodyInvoker.start` could try to synchronously add a body invoker after `DSL$ThreadTaskImpl.invokeBody` had completed (or in the middle of it, leading to things like the `ArrayIndexOutOfBoundsException` described in [this comment](https://issues.jenkins-ci.org/browse/JENKINS-58878?focusedCommentId=378651&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-378651)), but before the step has switched to async mode by calling `CpsStepContext.switchToAsyncMode` in `DSL$ThreadTaskImpl.eval`, and so the body invoker would be ignored forever, since the step had switched to async mode. This only appears to …

[JENKINS-58878] Make DSL$ThreadTaskImpl.eval and CpsBodyInvoker.start atomic with respect to both CpsStepContext.bodyInvokers and CpsStepContext.sync

---

CHANGELOG.md

I'd like to release this today along with pipeline-build-step to avoid any problems related to the first changelog item in https://github.com/jenkinsci/pipeline-build-step-plugin/pull/36.

Add release notes for 2.77 release

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

See [JENKINS-34256](https://issues.jenkins-ci.org/browse/JENKINS-34256).
I am not sure if this is the only problem described in that ticket, since there is some discussion there about specific steps, but as far as I can tell the problem was that once the `CpsThreadGroup` suspended itself because it detected that quiet mode was enabled, nothing will call `CpsThreadGroup.scheduleRun` other than pausing and unpausing the Pipeline or restarting Jenkins, so the build is just permanently suspended.
This PR fixes the issue by adding a listener that tracks `Jenkins.isQuietingDown` to detect when quiet down mode is cancelled so that it can call `CpsThreadGroup.scheduleRun` which will resume the build.
I'm not sure if there is a better way to do this, or if the current behavior is even the behavior …

[JENKINS-34256] Resume Pipeline execution if quiet mode is canceled

---

src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java

Previously `ParallelStep.ResultHandler.Callback.checkAllDone` made a `FailFastException` with no (`null`) message, then calls `ParallelStepExecution.stop`, which calls `BodyExecution.cancel(Throwable)`, which creates a `FlowInterruptedException` with an `ExceptionCause`, so the message is poor.
Amends https://github.com/jenkinsci/pipeline-plugin/pull/88.

Use FailFastCause to provide a nicer cause of failure

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

Should fix enforcer errors seen in the CI builds when testing against 2.222.x.
2.176.x is the fourth-oldest LTS line at this point, so it seems like a conservative enough upgrade. The core BOM used by version 4.x of the parent POM also supports 2.164.3 if we want to be even more conservative.

Fix build errors by updating minimum core version and parent POM

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

Essentially DRY for [DirectiveGeneratorTest](https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/d9f665d27c269f8294e3897f54f1f7d1f3d6a8e5/pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java#L587-L602). Upstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/396

Expose assertGenerateSnippet to pipeline-model-definition

---

src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

I find this useful to ensure backward compatibility when changing
symbols or step parameter names.

Add SnippetizerTester#assertParseStep

---

src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
src/test/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHackTest.java

See [JENKINS-62659](https://issues.jenkins-ci.org/browse/JENKINS-62659). Fixes https://github.com/cloudbees/groovy-cps/issues/105.
Groovy seems to have nondeterministic behavior when checking for category methods on types that implement more than one interface with the same name (e.g. `LinkedList`, which implements both `Deque` and `List`, each of which have an `iterator` method). Groovy picks one of the interfaces (via `MetaMethodIndex.getMethods`), and only checks for a matching category method for the chosen interface, which is problematic if the category method is only implemented for one of the interfaces and Groovy chooses the other one. 
In our case, this means that `new LinkedList(...).iterator()` sometimes calls `IteratorHack.iterator(List)` and so returns a serializable …

[JENKINS-62659] Fix iterator serialization errors for types that implement Deque

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java

See #367. This is the first alternative discussed in https://github.com/jenkinsci/workflow-cps-plugin/pull/367#discussion_r458869636.

[JENKINS-63164] Clear fields in CpsThread when thread is removed from CpsThreadGroup

---

CHANGELOG.md

I am planning on releasing the plugin today. Only change is #368, so in case something goes wrong with that change we can just block the release from the update center without needing to worry about other changes that users might care about.

Add 2.82 release notes

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

See [JENKINS-55287](https://issues.jenkins-ci.org/browse/JENKINS-55287).
While looking through some potentially-relevant code for that issue, I noticed that the logging when saving `CpsFlowExecutions` using the `PERFORMANCE_OPTIMIZED` durability level was a bit inconsistent, didn't really have a single clear message of whether everything was successful or not, didn't log anything for a few conditions that should never happen, used a default impl of `toString` (e.g. `MyClass@hash`) in some cases that were intending to print the name of the flow execution, and mentioned shutdown in some cases where Jenkins isn't shutting down.
~Opening as a draft PR for now, because I want to look through the logs of the tests before and after the change to see if anything interesting stands out, and maybe …

[JENKINS-55287] Improve shutdown-related logging

---

src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

See [JENKINS-63500](https://issues.jenkins-ci.org/browse/JENKINS-63500).
Doc generation fails for the `input` step in new versions of Jenkins, so we switch this test over to a different step that doesn't have anything to do with parameters to avoid the issue.
https://github.com/jenkinsci/workflow-cps-plugin/commit/e2b1c95be13c17fc3dbf15cb55a55e16ffa217fc just moves some imports around, and https://github.com/jenkinsci/workflow-cps-plugin/commit/f9f4918b6b5b397c9a2fde53d6d3671a2e87ef62 is the fix.

[JENKINS-63500] Fix SnippetizerTest.oneOrMoreArgsStepDocs in Jenkins 2.236 and newer

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

This PR is not a security fix, it just adds regression tests for various Pipeline-specific issues fixed by [SECURITY-2020](https://www.jenkins.io/security/advisory/2020-09-23/#SECURITY-2020) and [SECURITY-1658](https://www.jenkins.io/security/advisory/2019-11-21/#SECURITY-1658).

[SECURITY-1658][SECURITY-2020] Add regression tests for various exploits

---

CHANGELOG.md

accidentally put a release date on 2.85 when it is only being prepared for release

prepare changelog for 2.85 release

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/UninstantiatedDescribableWithInterpolation.java

There are some conditions in which the NamedArgsAndClosure class is passed to other packages where it is not recognized. This fix here goes back to an earlier implementation in #370  where we create a subclass of `UninstantiatedDescribable` that stores interpolated strings. This should ensure that existing code that used to look for `UninstantiatedDescribable` can continue to work as expected.
Note: not sure what tests to add to reflect this problem. Did manual testing with the Gerrit plugin

[JENKINS-64185] Replace use of NamedArgsAndClosure as return value for invokeDescribable

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

See [JENKINS-64282](https://issues.jenkins.io/browse/JENKINS-64282).
Empty string password parameters will trigger a false warning of groovy string interpolation

[JENKINS-64282] Skip if sensitive variable has an empty string

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java

[JENKINS-63305](https://issues.jenkins.io/browse/JENKINS-63305)
Pipeline job durability settings are ignored when lightweight checkout is used. This is due to an incorrect instance check of the `Queue.Executable`.

[JENKINS-63305] Fix bug that ignores durability settings with lightweight checkout

---

Jenkinsfile
pom.xml
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/workflow.css

This is a simplistic start at the tables to divs conversion for this plugin based on https://github.com/jenkinsci/scm-api-plugin/commit/0c2723bb5029805565ffe128b98bfca6574d418b . 
This may be all that is needed, but we should run tests against some downstream plugins just to be sure.

Handle tables-to-divs conversion

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java

Fix bug where `TreeMap.get()` was  used  instead of `EnvVars.get()`.
The difference being that `EnvVars.get()` provides a default value if the key  does not exists as opposed to just `null` with `TreeMap.get()`.

[JENKINS-64729] use EnvVars get() instead of TreeMap get()

---

src/test/java/org/jenkinsci/plugins/workflow/cps/ParamsVariableTest.java

Due to jenkinsci/jenkins#5275 a test breaks PCT and is blocking jenkinsci/bom#511.
Because now there is no way to produce a null value we skip the test on newer versions of jenkins
Tested manually with `mvn clean install -Djenkins.version=2.289`

Skip test if jenkins version is too new to fix PCT failure

---

src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.properties

[JENKINS-50855](https://issues.jenkins.io/browse/JENKINS-50855) has been a major source of confusion since #187.

[JENKINS-50855] Clearly differentiate between Replay and Rebuild

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java

As of https://github.com/jenkinsci/jenkins/pull/3009.

No need to override default `DescriptorByNameOwner.getDescriptorByName`

---

src/test/java/org/jenkinsci/plugins/workflow/SubtypeInjectingStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java

More breakage from jenkinsci/jenkins#5425, discovered when running PCT against a recent core incremental. This gets these tests to pass against both old and new cores.

Adapting `SubtypeInjectingStepTest`, `ArgumentsActionImplTest`, and `RestartingLoadStepTest` to jenkinsci/jenkins#5425

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java

I noticed in a `nodes/master/pipeline-thread-dump.txt` from a controller with lots of active agents (EC2, as it happens) that most of the file was taken up by `ExecutorStepExecution.status` content bloated by https://github.com/jenkinsci/jenkins/pull/2651:
```
Build: myprj #123
Thread #456
at DSL.node(waiting for part of myprj #123_somebranch to be scheduled; blocked: Waiting for pending items to get a node assigned; ‘agent1’ doesn’t have label ‘mylabel’; ‘agent2’ doesn’t have label ‘mylabel’; …47Kb later…)
at WorkflowScript.run(WorkflowScript:789)
at …
```
Adapted code from the [`junit` plugin](https://github.com/jenkinsci/junit-plugin/blob/74f8fdf99237e144b097830c2ddc6ea6d4c96b82/src/main/java/hudson/tasks/junit/CaseResult.java#L198-L212) for this.

Trim `StepExecution.status` to a sane length in stack traces

---

pom.xml

Mistake in #380. Noticed due to broken SCM URLs in deployed POM in #474.

Incorrect use of `gitHubRepo`

---

src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

Trying to diagnose an intermittent error when restoring builds from backup
```
Resuming build at … after Jenkins restart
[Pipeline] End of Pipeline
java.io.IOException: Unsupported protocol version 101
at org.jboss.marshalling.river.RiverUnmarshaller.start(RiverUnmarshaller.java:1349)
at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.readPickles(RiverReader.java:175)
at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.restorePickles(RiverReader.java:142)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.loadProgramAsync(CpsFlowExecution.java:784)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:750)
at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
at …
```

Verifying that a missing `program.dat` causes a comprehensible error

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

Adding a test case for [JENKINS-57253](https://issues.jenkins-ci.org/browse/JENKINS-57253). The last assertion currently fails due to a leaked executor, as described in the bug, so I have marked the test with `@Ignore`. When the bug is fixed, the `@Ignore` annotation can be removed.

Test case for JENKINS-57253

---

src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

[JENKINS-67380](https://issues.jenkins.io/browse/JENKINS-67380)

[JENKINS-67380] Detect oversized maps, collections and arrays and truncate

---

pom.xml

With recent versions of Maven Enforcer, any plugin depending on `workflow-cps` starts getting errors like this:
```
Require upper bound dependencies error for javax.servlet:servlet-api:0 [provided] paths to dependency are:
+-org.jenkins-ci.plugins:gitlab-plugin:1.5.25-SNAPSHOT
+-org.jenkins-ci.plugins.workflow:workflow-cps:2.94 [test]
+-org.jenkins-ci.ui:ace-editor:1.1 [test] (managed) <-- org.jenkins-ci.ui:ace-editor:1.1 [test]
+-javax.servlet:servlet-api:0 [provided] (managed) <-- javax.servlet:servlet-api:2.4 [provided]
```
While the root cause of the problem is that `ace-editor` needs refreshing, excluding the problematic `provided` version of `javax.servlet:servlet-api` in `workflow-cps` at the point that `ace-editor` is consumed is easily a fraction of the work and chases away the …

Exclude `javax.servlet:servlet-api`

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

When you see something like
```
"Computer.threadPoolForRemoting [#…]" Id=… Group=main RUNNABLE
at java.util.ArrayList.iterator(ArrayList.java:842)
at hudson.ExtensionList.iterator(ExtensionList.java:170)
at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter$1.writeReplace(RiverWriter.java:124)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:190)
at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
at …
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
at …
```

Record which `program.dat` is being saved in a thread dump

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

Updates the plugin parent POM to the latest LTS, along with updating the plugin BOM accordingly. This is necessary in order to be able to test this plugin on Java 17, as I am trying to do in https://github.com/jenkinsci/bom/pull/935. With these changes I can run `mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.cps.ContextVariableSetTest,org.jenkinsci.plugins.workflow.cps.CpsBodyExecutionTest,org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition2Test,org.jenkinsci.plugins.workflow.cps.CpsThreadDumpActionTest -Djenkins-test-harness.version=1721.v385389722736 '-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED'` on Java 17 and they don't quite …

Update plugin parent POM and plugin BOM

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

https://issues.jenkins.io/browse/JENKINS-68071
Amends #32. Relevant test coverage is in `CpsFlowExecutionTest`. Fixes the Java 17 run of
```bash
mvn test -Dtest=org.jenkinsci.plugins.workflow.cps.CpsThreadDumpActionTest\#doProgramDotXml -Djenkins.version=2.339 -Djenkins-test-harness.version=1721.v385389722736 '-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED'
```
printing as expected
```xml
<executionPaused>false</executionPaused>
```

[JENKINS-68071] Java 17 compat: make `CpsThreadGroup.paused` `transient` to avoid XStreaming `AtomicBoolean`

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

On Java 17, run `mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.cps.CpsBodyExecutionTest,org.jenkinsci.plugins.workflow.cps.CpsThreadDumpActionTest -Djenkins.version=2.339 -Denforcer.skip -Djenkins-test-harness.version=1723.vcd938b_e66072 '-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED'`
**Note:** These are the *actual* results when adding `--add-opens java.base/java.util.concurrent=ALL-UNNAMED` to the above arguments:
The test passes.
The test fails with:
```
com.thoughtworks.xstream.converters.ConversionException: 
No converter available
- Debugging information ----
message             : No converter available
type                : java.util.concurrent.ConcurrentSkipListMap
converter …
```

[JENKINS-68092] Serialization of `java.util.concurrent` data structure in Pipeline: Groovy

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

When using a large number of concurrent steps, writing timings back can
become a contention point as it locks the `CpsFlowExecution` object.
Replace the timings implementation by a concurrent map and only use atomic operations.

Use a concurrent map to manage timings

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

If a build is loaded from a saved state, and the build existed before #519 (i.e. v2686.v7c37e0578401), It is possible for the `timings` field to be `NULL`. This causes an NPE when the Timing is closed: https://github.com/jenkinsci/workflow-cps-plugin/blob/3f09155513c1c8ed3727ec16220701bee0c31a9c/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L432

Migrate from readResolve to unmarshal

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

See [JENKINS-63766](https://issues.jenkins.io/browse/JENKINS-63766) and upstream bug [JDK-8231454](https://bugs.openjdk.java.net/browse/JDK-8231454). Users have reported gradual exhaustion of the metaspace when running on Java 11 with Pipeline jobs that define custom classes.
Create a new Pipeline job with
```java
class asdf {
void run () {}
}
new asdf().run()
```
and run it under Java 11 with `-verbose:class`. After the job finishes, run `jcmd ${PID} GC.run`
**Note:** These are the _actual_ results when running under Java 8 or Java 17.
The `WorkflowScript` and `asdf` classes get unloaded.
The `WorkflowScript` and `asdf` classes never get unloaded on Java 11.
As described in the upstream bug, a memory memory leak can occur when `java.beans.Introspector#getBeanInfo` is invoked against a …

[JENKINS-63766] Work around JDK-8231454

---

src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

See [JENKINS-45327](https://issues.jenkins.io/browse/JENKINS-45327).
Right now, if you use `env` in a Pipeline in a way that causes `EnvActionImpl` to be serialized into the program's state, then after resumption you end up with a distinct instance of `EnvActionImpl` that is unrelated to the action attached to the `WorkflowRun`, so the `owner` for the deserialized `EnvActionImpl` is null, and `getProperty` and `setProperty` throw NPEs.
This PR fixes the issue by pickling `EnvActionImpl` so that it can be rehydrated using the action attached to the `WorkflowRun`, which maintains the expected singleton semantics and prevents issues.

[JENKINS-45327] Pickle EnvActionImpl to prevent multiple instances from existing after resumption

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

Amending #490, and a string of earlier attempts to log repeated attempts to mark a step as failed, all of which had problems. Most recently, in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 I find a case where first a `node` block is marked failed by `FlowInterruptedException`, and then a nested `sh` step throws `MissingContextVariableException` as well. Harmless; can use `addSuppressed` to at least track everything.

Never print warnings from `CpsStepContext.completed`, but use `addSuppressed`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/221 and required to avoid regressions in some corner cases.

Defer being “ready to run” until `StepExecution.onResume`s complete

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java

Seems the tricks explored in https://github.com/jenkinsci/jenkins/pull/6643 & https://github.com/jenkinsci/support-core-plugin/pull/376 are not necessary if code logging at fine levels takes care to use `Supplier`-based overloads (or otherwise convert record parameters to `String`, as in #41) where the parameters might refer to expensive object trees.
<details>
<summary>Sketch of iterative testing</summary>
```bash
mvnd -Pquick-build -f jenkins -pl core clean install
mvnd -Pquick-build -f support-core-plugin install
mvnd -Pquick-build -f workflow-cps-plugin install
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 mvn -f pipeline-groovy-lib-plugin test -Dtest=LibraryMemoryTest
```
given
```diff
diff --git pom.xml pom.xml
index 9ee4e40..66b4259 100644
--- pom.xml
+++ pom.xml
@@ -63,15 +63,15 @@ …
```

[JENKINS-68417] Use `Supplier` overloads to avoid leaks from `LogRecord.parameters`

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/124.

[JENKINS-49707] Implement `BodyExecution.cancel(Throwable)`

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

Only used in test code, and there is generally a better way. (CC @riliane)
Not trying to clean up all usages (in this and other plugins) at this time.
https://github.com/jenkinsci/workflow-cps-plugin/pull/340#discussion_r353308803 https://github.com/jenkinsci/pipeline-plugin/pull/249 https://github.com/jenkinsci/workflow-cps-plugin/pull/568#discussion_r929157142

Deprecating `waitForSuspension`

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

A race condition in `FlowDurabilityTest.testResumeBlockedAddedAfterRunStart` caused the test to flake.
```
org.junit.ComparisonFailure: expected:<[sleep]> but was:<[End of Pipeline]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest.assertIncludesNodes(FlowDurabilityTest.java:665)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest$23.evaluate(FlowDurabilityTest.java:788)
```
The last "sleep" node was not loaded on restart.
Even though all individual nodes were persisted properly, a change to the head node ID was being done by another thread and was not completing before the original thread went on to restart Jenkins.
`CpsThreadGroup.notifyNewHead` starts a thread every time it …

Resolve a race condition in FlowDurabilityTest causing test flakes

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/main/resources/images/symbols/pause.svg
src/main/resources/images/symbols/redo.svg
src/main/resources/org/jenkinsci/plugins/workflow/cps/PauseUnpauseAction/action.jelly

The change proposed makes use of the centralized ionicons API to remove the need to ship symbols on a per-plugin basis, that are provided by the library.
cc @jenkinsci/workflow-cps-plugin-developers

feat: Switch to ionicons api

---

src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

`testDurableAgainstCleanRestartFailsWithDirtyShutdown` occasionally throws an NPE and flakes, because the build.xml file of the run ends up empty after being interrupted by a dirty restart, as the writes for performance-optimized durability are not atomic. That's still a kind of run failure and a plausible consequence of a dirty restart, so I propose to accept this outcome and skip all the remaining assertions.
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Accept run not loading at all as a kind of run failure in testDurableAgainstCleanRestartFailsWithDirtyShutdown

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java

https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/195/commits/19c2fdeab67597016b9cb960cda999839421d112 turned up a curious test failure. It turned out that a synchronous nonblocking step completed long after Jenkins had shut down, but since the test uses `JenkinsSessionRule` rather than `RealJenkinsRule`, the JVM continued running and the completion was actually processed by finishing the build (successfully) in the old copy of Jenkins. Needless to say, things got confused when the same build in the new copy of Jenkins tried to continue running, and began doing stuff with the still uncompleted program state despite the build record on disk claiming the build had completed.
There are probably multiple things that could be fixed here (and I will try to make the test behave more …

Call `CpsVmExecutorService.shutdown` from `CpsFlowExecution.suspendAll`

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

See https://issues.jenkins.io/browse/JENKINS-55287
Update the exception message when FlowNode fails to load because Jenkins did not shut down cleanly. Suggest pipeline durability MAX_SURVIVABILITY if not already set.

[JENKINS-55287] update exception warning for failure to load flow node

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

The workaround introduced in #543, while harmless on Java 11.0.17, is no longer necessary (because the fix was backported to 11.0.17 and later). Therefore, skip the workaround on those releases. If accepted I will open another PR to apply the same copypasta to `script-security`. To test this change, I stepped through the code in the debugger and verified that we applied the workaround on 11.0.16 but not on 11.0.17 or 17.0.4.

Workaround for JDK-8231454 on Java 11 is no longer necessary as of 11.0.17

---

.github/dependabot.yml
README.md
package.json
yarn.lock

Follow up to https://github.com/jenkinsci/workflow-cps-plugin/pull/581
Visual testing didn't reveal any regressions, additionally, I added an entry to the dependabot configuration, to handle future updates automatically.

Update a few frontend dependencies

---

.github/dependabot.yml

Follow up to https://github.com/jenkinsci/workflow-cps-plugin/pull/604
Looks like npm inherits yarn's settings by now.

Fix dependabot ecosystem

---

pom.xml

Picking up https://github.com/jenkinsci/workflow-cps-plugin/pull/601#issuecomment-1296983973
@jglick 4.49 removed the default the versions set for yarn, node and npm. This repository uses all three tools, but did declare `<node.version>` and `<npm.version>` only.
This PR demonstrates how to upgrade to 4.49 by specifying `<yarn.version>`.
I'll add a few links to the 4.49 changelog where to obtain these versions from. I'd assume that makes it easier for users to upgrade?
Closes https://github.com/jenkinsci/workflow-cps-plugin/pull/601

Bump plugin from 4.48 to 4.49

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyClassLoaderWhitelist.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

See [JENKINS-69905](https://issues.jenkins.io/browse/JENKINS-69905) and https://github.com/jenkinsci/workflow-cps-plugin/commit/1af77ffcc773ffac4eb49956168b9778dca9a3b6. Because `script-security` only requires Jenkins 2.332.1, users running Jenkins 2.332.x who install `script-security` and `workflow-cps` from the plugin manager will end up with incompatible versions (`script-security` will have the SECURITY-2824 fix, but `workflow-cps` will not). There is not currently an easy way to directly control the version of `script-security` offered to 2.332.x users (so that we could offer them the most recent version without the SECURITY-2824 fix), so instead we decided to just backport the SECURITY-2824 changes to the last version of `workflow-cps` that supports 2.332.x.
In retrospect, we should …

[JENKINS-69905] Backport SECURITY-2824 for Jenkins 2.332.x users

---

lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/ListBlock.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/SpreadBlock.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/SpreadMapBlock.java
lib/src/test/java/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.java
lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java

See [JENKINS-46163](https://issues.jenkins.io/browse/JENKINS-46163). This PR is a copy of https://github.com/cloudbees/groovy-cps/pull/123, which was based on https://github.com/cloudbees/groovy-cps/pull/116.
We follow the same approach as regular Groovy for `SpreadMapExpression` (the expression gets turned into a special `SpreadMap` by [`InvokerHelper.spreadMap`](https://github.com/apache/groovy/blob/41b990d0a20e442f29247f0e04cbed900f3dcad4/src/main/org/codehaus/groovy/runtime/InvokerHelper.java#L378), and then Map literals are constructed using [`InvokerHelper.createMap`](https://github.com/apache/groovy/blob/41b990d0a20e442f29247f0e04cbed900f3dcad4/src/main/org/codehaus/groovy/runtime/InvokerHelper.java#L399) which detects this marker class and interpolates it).
We use a similar …

[JENKINS-46163] Add support for spread and spread-map operators

---

.github/dependabot.yml
dgm-builder/pom.xml
pom.xml

Make Dependabot ignore Groovy and do not specify explicit remoting version in groovy-cps-dgm-builder

---

lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
lib/src/main/java/com/cloudbees/groovy/cps/impl/CastBlock.java
lib/src/test/java/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.java
lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java

See [JENKINS-70108](https://issues.jenkins.io/browse/JENKINS-70108).
https://github.com/jenkinsci/workflow-cps-plugin/commit/819cc9be597121a2bf88b7669323aa6caa502f72 introduced a new `Block` for casts, `CastBlock`, which did not implement `CallSiteBlock` and did not contextualize its `Invoker`. In cases where untrusted code calls trusted code that performs a cast, this could result in trusted code calling `SandboxInvoker.cast` instead of `DefaultInvoker.cast`. In practical terms, this means that casts inside of global Pipeline libraries were sometimes incorrectly blocked by the sandbox.
This PR makes `CastBlock` implement `CallSiteBlock` so that it can contextualize `Invoker` correctly before performing the cast.
TODO:
* I am pretty sure that it technically does, but the current code …

[JENKINS-70108] CastBlock must contextualize invoker to avoid issues in mixed-trust scenarios

---

plugin/src/main/js/workflow-editor.js

See [JENKINS-70564](https://issues.jenkins.io/browse/JENKINS-70564).
1. When multiple Ace editors are on a single page (for example, when replaying a Pipeline with a non-trusted shared library), only the first editor loads. This is a regression.
2. Every page with an Ace editor shows log spam of the form "Unable to infer path to `ace` from script `src`, use `ace.config.set('basePath', 'path')` to enable dynamic loading of modes and themes or with `webpack` use `ace/webpack-resolver`"
1. This is a Stapler "adjunct" which is a pair of CSS and JavaScript as in https://github.com/jenkinsci/stapler/blob/70d5f5f9064f527e3fe19671d827857de410d05e/jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/Adjunct.java#L204-L207. The way Webpack works, the script is only loaded a single time. In the …

[JENKINS-70564] Replay page broken after the Ace editor update

---

plugin/src/main/js/workflow-editor.js

https://github.com/jenkinsci/workflow-cps-plugin/pull/653#issuecomment-1424299833 was an assertion without evidence, and also an incorrect one — the cause of [JENKINS-70591](https://issues.jenkins.io/browse/JENKINS-70591) was #656, **not** #653. This was determined after a few minutes of bisection. Using the [JQuery `ready()` API](https://api.jquery.com/ready/) gets rid of this bug and is consistent with the code elsewhere in this file which uses JQuery rather than plain JavaScript. Note that I followed the recommended syntax:
> jQuery offers several ways to attach a function that will run when the DOM is ready. All of the following syntaxes are equivalent:
>
> - `$( handler )`
> - `$( document ).ready( handler )`
> - `$( "document" ).ready( handler )`
> - `$( "img" ).ready( handler )`
> …

[JENKINS-70591] Cannot create inline Pipeline job after Ace editor upgrade

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

When considering loading libraries from JAR files in https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/55 it occurred to me that a completed build might leave classpath JAR files open at least until garbage collection, which could be a problem particularly on Windows. Might also affect Grape users. Safest to close these deterministically. Untested beyond the many functional tests in this plugin.

Call `GroovyClassLoader.close` when build completes

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Extending #667 to the case that something failed in `parseScript`, addressing some Windows test failures in https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/57.

Call `GroovyClassLoader.close` also if build never starts

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

https://github.com/jenkinsci/workflow-cps-plugin/pull/519#discussion_r838633990 looked reasonable, yet there have been field reports of lock contention here. (Complements https://github.com/jenkinsci/blueocean-plugin/pull/2406.) Since gathering of timing information is done on a best-effort basis, and is used only for support diagnostics, it is preferable to risk the occasional clobbered update from two threads (effectively losing one delta) than to ever acquire a lock.

Lockless `Timing.close`

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionRJRTest.java

Right now, when Jenkins shuts down gracefully, we attempt to pause Pipeline execution and save all related state information. However, we do not flush the listener for the overall log, which means that for `LogStorage` implementations like `FileLogStorage` that write the log and log metadata to separate files, and write metadata synchronously while buffering log writes, the metadata and log file may be out of sync after a Jenkins restart.
In particular, when performing a safe restart, we write ["Pausing (Preparing for shutdown)"](https://github.com/jenkinsci/workflow-cps-plugin/blob/43ba38b62bb731c7dffccbc6e975732719f708a2/plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java#L308) to the build log and pause the Pipeline. For `FileLogStorage`, if the last log line …

Flush overall Pipeline log stream when shutting down Jenkins

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java

https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/57#issuecomment-1457112652

More efficient `JarURLConnection` implementation

---

dgm-builder/pom.xml
lib/pom.xml
pom.xml

Subsumes #685 but should allow https://github.com/jenkins-infra/repository-permissions-updater/pull/3210 to be reverted, cleaning up technical debt from #612. Local testing seems fine using both a clean working copy and a clean local repo:
```bash
mvn clean test -Dtest=CpsDefaultGroovyMethodsTest
```

Support PCT for multi-module Maven projects (II)

---

dgm-builder/pom.xml
lib/pom.xml
pom.xml

For the forthcoming support for multi-module Maven projects in PCT, we are planning on running at the root of each Maven multi-module project:
```
$ mvn […] clean process-test-classes  # compile test classes against original production classes
$ mvn -Djenkins.version=${LATEST_WEEKLY} -DoverrideWar=${MEGAWAR} […] hpi:resolve-test-dependencies hpi:test-hpl surefire:test  # run tests against new versions
```
The idea is to use the original production classes for the compatibility test, compiling the test classes against them for the most realistic compatibility test. This is how PCT already works today for flat Maven projects, so we are extending this to multi-module Maven projects. When run in the root of `workflow-cps`, this fails in `lib/` because compiling the test classes depends on …

Support PCT for multi-module Maven projects

---

dgm-builder/pom.xml
lib/pom.xml

Reverting #689 beyond #685. Issue reproducible outside PCT as
```bash
mvn -Pquick-build package -am -pl plugin
```
since 7fc22238d80bd17031c0df7b4b94ec399bac1f20 makes Maven think this need not be built. I think there is a way to build & deploy `dgm-builder` normally without needing an überjar (the plain JAR is tiny), but it would take some more time to prepare those changes and it would be easier to experiment with that once the dust has settled on PCT.
Likely needs https://github.com/jenkins-infra/repository-permissions-updater/pull/3219 to build.

Restore deployment of `dgm-builder`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Already in `PipelineThreadDump` for running builds, but seems also useful to know for completed builds, especially when you are wondering if there is a reason why some pathologically large timings are being displayed.

Add `CpsFlowExecution.approximateNodeCount` to `PipelineTimings`

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

Seen recently in PCT:
```
org.apache.commons.io.IOExceptionList: …/plugin/target/tmp/j h9111237813030279202/jobs/testJob/builds/1/workflow
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.lambda$inProgressButFlowNodesLost$16(PersistenceProblemsTest.java:296)
at …
Caused by: java.io.FileNotFoundException: File does not exist: …/plugin/target/tmp/j h9111237813030279202/jobs/testJob/builds/1/workflow/atomic5190200290324607044tmp
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1349)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
... 9 more
```
Seems like some sort of background process is running which …

Flake in `PersistenceProblemsTest.inProgressButFlowNodesLost`

---

.github/dependabot.yml
README.md
plugin/.eslintrc.js
plugin/package.json
plugin/pom.xml
plugin/src/main/js/snippets/workflow.js
plugin/src/main/js/workflow-editor.js
plugin/webpack.common.js
plugin/webpack.dev.js
plugin/webpack.prod.js
plugin/yarn.lock

Some changes developed working on the editor a few weeks back but never submitted. See self-review for explanation. To test this change, I installed the plugin and verified I could edit Pipeline configuration with no regressions. I confirmed that the production build was optimized and undebuggable (the status quo). With
```json
diff --git a/plugin/package.json b/plugin/package.json
index e10359b7..731ecf14 100644
--- a/plugin/package.json
+++ b/plugin/package.json
@@ -10,7 +10,7 @@
"prod": "webpack --config webpack.prod.js",
"start": "yarn dev -- --watch",
"lint:js": "eslint src/main/js --ext js",
-    "mvnbuild": "yarn prod",
+    "mvnbuild": "yarn dev",
"mvntest": "yarn lint:js"
},
"repository": {
```
I rebuilt the plugin and confirmed that I could do in situ debugging of the …

Clean up Webpack build

---

plugin/pom.xml
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
pom.xml

Require Jenkins 2.387.3 or newer so that we can use HTMLUnti 3.x and so that users are not mislead to believe we are testing older versions.
- Depend on git plugin 5.1.0 for HTMLUnit 3 upgrade
Includes pull requests:
* #719
Supersedes pull requests:
* #706
Tests pass locally with Java 11 on Linux.  Will install on my Jenkins controller after an incremental build is available.

Require Jenkins 2.387.3 or newer

---

plugin/pom.xml

Restore missing `<scope>test</scope>` to `git`

---

plugin/src/main/js/samples.js
plugin/src/main/js/workflow-editor.js
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly

See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), went to the Pipeline Editor, verified that correct …

Replace Prototype.js with native JavaScript

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly

The change proposed adapts core changes, such as https://github.com/jenkinsci/jenkins/pull/7634, moving to the `one-column` layout, you can find already in various core pages.
Before:
After:

Adapt 'one-column' design in thread dump

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/workflow.js

Forgotten in #702. Attempting to view the Steps Reference in the UI with Prototype disabled results in
```
Uncaught ReferenceError: $$ is not defined
parseDom http://127.0.0.1/adjuncts/0ce4ef4c/org/jenkinsci/plugins/workflow/cps/Snippetizer/workflow.js:3
<anonymous> http://127.0.0.1/adjuncts/0ce4ef4c/org/jenkinsci/plugins/workflow/cps/Snippetizer/workflow.js:26
```
Fixed by converting this file to native JavaScript. I also verified there were no other usages of Prototype that I missed. To test this, I reproduced the problem in the Steps Reference view and verified that it could no longer be reproduced after this PR by expanding and contracting steps in the UI.

Remove usages of Prototype from Steps Reference

---

plugin/.eslintrc.js
plugin/package.json
plugin/src/main/js/workflow-editor.js
plugin/yarn.lock

Core dropped support for older browsers some time ago, but this plugin was never updated to match. See inline review for a detailed explanation of changes. To test this PR I did a full build and then successfully edited Pipeline configuration in the UI.

Drop support for ancient web browsers

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/gdsl.groovy

Calling https://localhost/pipeline-syntax/gdsl creates a document that escapes forward slashes. 
The use of `groovy.json.StringEscapeUtils.escapeJavaScript(java.lang.String)`, will break parsing of the resulting content within an IDE (i.e. IntelliJ Idea), if described plugin steps have a forward slash in their `displayName` content.
plugin samples: 
- step `envVarsForTool` of plugin "pipeline-model-definition" (contains single quote) [Link](https://www.jenkins.io/doc/pipeline/steps/pipeline-model-definition/)
- step `sshGet`, `sshPut` of plugin "ssh-steps" (contain forward slash) [Link](https://www.jenkins.io/doc/pipeline/steps/ssh-steps/)
According to Groovy API doc of [escapeJavaScript](https://docs.groovy-lang.org/latest/html/api/groovy/json/StringEscapeUtils.html#escapeJavaScript(java. …

Fix generated gdsl code display names

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly

I tried to click on the `program.xml` link for a thread dump from a build which was still stuck loading pickles, hoping to get information about those pickles, but the web request simply timed out:
```
"Handling GET …/threadDump/program.xml from … TIMED_WAITING on java.util.concurrent.CompletableFuture$Signaller@88c1e6d
at java.base@11.0.20/jdk.internal.misc.Unsafe.park(Native Method)
-  waiting on java.util.concurrent.CompletableFuture$Signaller@88c1e6d
at java.base@11.0.20/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
at java.base@11.0.20/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
at java.base@11.0.20/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
at …
```

`…/threadDump/program.xml` hangs when program still loading pickles

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Drops support for OpenJDK versions older than 11.0.17 on the 11 LTS line and 17.0.4 on the 17 LTS line, both now about a year old. The impact when running without these workarounds on older OpenJDK versions is that you may be subject to memory leaks. It seems worth it to simplify this hard-to-maintain reflection-based code and drop support for these older runtime environments. See also https://github.com/jenkinsci/jenkins/pull/8193.

Remove unnecessary workarounds

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java

Have seen a test flake in PCT:
```
java.lang.AssertionError
at org.jenkinsci.plugins.workflow.cps.CpsThread.getStackTrace(CpsThread.java:330)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDump$ThreadInfo.<init>(CpsThreadDump.java:68)
at org.jenkinsci.plugins.workflow.cps.CpsThreadDump.from(CpsThreadDump.java:150)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.getThreadDump(CpsThreadGroup.java:515)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getThreadDump(CpsFlowExecution.java:1090)
at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecutionTest.getStatus(GeneralNonBlockingStepExecutionTest.java:79)
```
https://github.com/jenkinsci/workflow-step-api-plugin/blob/6ecacd8c04aa1326eab48553730541b0abc9c1f9/src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNo …

Assertion error from `CpsThread.getStackTrace`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Observed during shutdown:
```
WARNING	o.j.p.w.cps.CpsFlowExecution#suspendAll: Error persisting Pipeline execution at shutdown: null
java.lang.IllegalStateException: build storage unloadable, or build already finished
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.runInCpsVmThread(CpsFlowExecution.java:928)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.suspendAll(CpsFlowExecution.java:1719)
```
Not sure what the exact conditions were here, but if we know `programPromise == null` there is no point in even trying to call `CpsThreadGroup.shutdown`. Amending #540.

`CpsFlowExecution.suspendAll` could log ISE

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

[JENKINS-59743](https://issues.jenkins.io/browse/JENKINS-59743) (at least new report from @timja): mistake in #534 affecting controllers that were restarted more than once in quick succession, not unusual in Kubernetes for example.

[JENKINS-59743] Restarting before `afterStepExecutionsResumed` could leave a build paused

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globals.groovy
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy

Forward compatibility, as these won't work when we switch from `javax` to `jakarta` imports anyway. One of these imports was unused, and the other was used for a variable for which we only checked nullness, so `def` suffices here.

Avoid `javax` imports in Groovy views

---

lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java

See [JENKINS-71818](https://issues.jenkins.io/browse/JENKINS-71818). Forward compatibility with [JDK-8268698](https://bugs.openjdk.org/browse/JDK-8268698) / https://github.com/openjdk/jdk/pull/4507.
Ran `mvn clean verify` on Java 11, 17, and 21. Before this PR, it failed on Java 21. After this PR, it passes on all three Java versions.

[JENKINS-71818] `CpsTransformerTest` fails on Java 21

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/301. Should make shutdown processes more predictable, since I found that `Reactor` uses a `HashSet` of tasks and thus runs terminators in a truly random order (though serialized in one thread!) unless you explicitly order them.

Honoring termination milestones

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

PCT caught a regression in #228 `BuildTriggerStepTest.storedForm`
```
java.lang.NullPointerException
at java.base/java.util.TreeSet.addAll(TreeSet.java:300)
at java.base/java.util.TreeSet.<init>(TreeSet.java:160)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$ConverterImpl.marshal(CpsFlowExecution.java:1718)
```
If loading a rather old `build.xml`, make sure to initialize `internalCalls` to an empty set.

NPE related to `internalCalls`

---

doc/classloader.md
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

A user reported not seeing the option for **Serialized program state** in a virtual thread dump. They are running `3713.vd671d4321509` (prior to #755). I suspect that they may have had `ADMINISTER` without `RUN_SCRIPTS`. Since this permission is deprecated, I think we just need to check the new permission.

Switch from `RUN_SCRIPTS` to `ADMINISTER`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Amends #228. There is no need to print _did not yet start_ warnings for hard-killed builds in this context.

Avoid `FlowExecutionOwner.get` from `PipelineInternalCalls`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

See [JENKINS-71692](https://issues.jenkins.io/browse/JENKINS-71692).
If there is a fatal error in the CPS VM thread, currently running steps should be given a chance to stop before we kill the build, otherwise async steps will just keep running in the background. Things can get very messy since the execution and run associated with the `StepExecution` will already be dead, and some steps like `node` and `stage` will just run forever if we do not stop them.
```[tasklist]
```

[JENKINS-71692] Attempt to stop step executions if the CPS VM thread dies with a fatal error

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

`FlowDurabilityTest.testResumeBlocked` and `.testResumeBlockedAddedAfterRunStart` frequently fail in PCT
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest.verifyExecutionRemoved(FlowDurabilityTest.java:219)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest.verifyCompletedCleanly(FlowDurabilityTest.java:370)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest.verifyFailedCleanly(FlowDurabilityTest.java:344)
at org.jenkinsci.plugins.workflow.cps.FlowDurabilityTest$21.evaluate(FlowDurabilityTest.java:778)
```
```
java.lang.AssertionError
at …
```

Remove flaky assertion from `FlowDurabilityTest.verifyExecutionRemoved`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

I noticed that in this code path we use the upstream XStream default driver rather than the controller-wide default driver defined by `hudson.util.XStream2#getDefaultDriver()`. The latter is commonly used throughout Jenkins, so it seems desirable to increase consistency by using it in this code path as well. Note that `new XStream2()` cannot be used here, because of JEP-200 violations.

Use controller-wide default XStream driver where possible

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowFactoryAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java

Added `@Deprecated` where `@deprecated` already in Javadoc

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Caught and logged as a warning from `FlowExecutionList.StepExecutionIteratorImpl` when trying to call `StepExecution.applyAll` at a certain point during shutdown, for example from `DurableTaskStep$AgentReconnectionListener.check` if an agent is disconnected. In fact that listener does check `Jenkins.get().isTerminating()` to avoid noise, but unfortunately this flag is set by `Jenkins.cleanUp` _after_ running `@Terminator`s (and before all other cleanup steps).

`RejectedExecutionException` from `CpsFlowExecution.getCurrentExecutions`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Continuing #215.
Without the main patch, you get the reported error in the system log
```
WARNING	o.j.p.w.cps.CpsVmExecutorService#reportProblem: Unexpected exception in CPS VM thread: CpsFlowExecution[Owner[p/1:p #1]]
java.lang.IllegalStateException: JENKINS-50407: no loaded shell in CpsFlowExecution[Owner[p/1:p #1]]
at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:35)
at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
at …
```

[JENKINS-50407] Better diagnosis for certain fatal loading errors

---

plugin/src/main/js/workflow-editor.js

This code introduced in #769 is breaking the local build. ~Not sure why it did not at the time; maybe there is some dependency not being pinned properly?~ As per https://github.com/jenkinsci/plugin-pom/issues/874 this is not caught by CI.

Suppress ESLint warning `no-unused-vars`

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/NotBlock.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
pom.xml

Will be needed with parent pom 4.77.
Confirmed that the spotbugs warnings are visible when using the 4.77-SNAPSHOT plugin pom before this change.  With this change, the spotbugs warnings are no longer visible.
```[tasklist]
```

Suppress warnings for spotbugs 4.8.3

---

plugin/pom.xml
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
pom.xml

Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.

Forward compatibility with Guice 7

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

The handling for a broken build in #809 seems to have been broken in the situation which #812 failed to reproduce:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script3: 8: unable to resolve class XXX 
@ line 8, column 5.
XXX xxx = null
^
Script3: 10: unable to resolve class XXX 
@ line 10, column 20.
void xxx(XXX xxx) {
^
2 errors
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:981)
at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:575)
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
at …
```

More robust `CpsFlowExecution.croak`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

https://issues.jenkins.io/browse/JENKINS-71926 since I just stumbled across this myself recently when I tried to use a NUL in a script passed to `sh` and accidentally passed that in the `script` instead.

[JENKINS-71926] Robustness against NULs in `ArgumentsActionImpl`

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/handle-prototype.js
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly

The CSRF crumb header can be configured on Jenkins via the java property `hudson.security.csrf.requestfield`.
When an instance overrides the header value with something different than `Jenkins-crumb`, the snippet generator would still use the hard-coded value, causing a 403 to be returned and no snippet to be displayed
On a Jenkins version 2.440.1 on a Debian 12 machine, Jenkins was started with `-Dhudson.security.csrf.requestfield=X-Jenkins-crumb`. 
Then on the https://jenkins.exemple.com/job/example/pipeline-syntax/ page, the `Generate Pipeline Script` button is clicked. 
Without this patch, the AJAX calls gets a 503, as the sent header is `Jenkins-crumb`. With the patch applied (I built a custom version of the plugin locally with Maven), the header is sent as configured by the Java …

Fix snippet generator when a custom crumb header is configured

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Finally tracked down the error noted in #812. Could reproduce by
<details>
<summary>Test patch</summary>
```diff
diff --git plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
index 69c2399d..00d050b4 100644
--- plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
+++ plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
@@ -150,6 +150,7 @@ import org.codehaus.groovy.GroovyBugError;
import org.jboss.marshalling.reflect.SerializableClassRegistry;
import static com.thoughtworks.xstream.io.ExtendedHierarchicalStreamWriterHelper.startNode;
+import java.util.Comparator;
import static org.jenkinsci.plugins.workflow.cps.persistence.PersistenceCon …
```

Reparse `CpsFlowExecution.loadedScripts` in original order

---

lib/src/main/java/com/cloudbees/groovy/cps/Continuable.java
lib/src/test/java/com/cloudbees/groovy/cps/CpsDefaultGroovyMethodsTest.java
lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
lib/src/test/java/com/cloudbees/groovy/cps/impl/NotBlockTest.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionMemoryTest.java

Follows up #124 / https://github.com/cloudbees/groovy-cps/pull/56 by calling `GroovyCategorySupport.use` only once per thread, rather than on every chunk.
Background: `CpsVmExecutorService` has a subtle design in that it is physically hosted on a fairly generic elastic thread pool; the CPS VM “thread” associated with a Pipeline build is virtual (does not correspond to any permanent Java `Thread`) and just makes use of some free physical thread whenever it has a chunk of work to run. Typically a chunk would involve as much Groovy logic as can run synchronously (milliseconds’ worth, you hope), up to the point where an asynchronous operation needs to take place, such as starting a step. (`parallel` is actually coöperative multitasking: step implementations can certainly run concurrently, but …

More efficient use of `GroovyCategorySupport`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java

I'm currently doing some work in core relating to the `Action` class and the way we present them. When doing so I was doing a basic check on `getIconFileName` to see if it was null, if null don't show the action. However the `Pipeline Syntax` action was always invisible as it has `getIconFileName` set to null and is not overridden, instead setting a custom method `getIconClassName`.
This PR instead overrides the `getIconFileName` method and it appears as expected.
* Icon/action shows as expected
```[tasklist]
```

Override 'getIconFileName' rather than setting 'getIconClassName'

---

dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java

Without this PR, Maven reproducible build verification fails with e.g.
```
├── com/cloudbees/groovy/cps/CpsDefaultGroovyMethods.java
│ @@ -39,15 +39,15 @@
│  import org.codehaus.groovy.runtime.GroovyCategorySupport;
│  import org.codehaus.groovy.runtime.InvokerHelper;
│  import org.codehaus.groovy.runtime.ReverseListIterator;
│  import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
│  import org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation;
│  import org.codehaus.groovy.util.ArrayIterator;
│  
│ -@Generated(value = "com.cloudbees.groovy.cps.tool.Translator", date = "Fri Apr 12 13:32:51 PDT 2024", comments = "based on groovy-cps-dgm-builder-3900.ved80eb_b_c18cf-jar-with-dependencies.jar")
│ +@Generated(value = "com.cloudbees.groovy.cps.tool.Translator", date = "Fri …
```

Support Maven reproducible builds

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/sidepanel.jelly

Small one to make a few adjustments to the interface of Pipeline Syntax:
* Up link removed from sidebar
* 'Overview' now shows as a `h1` - same as other pages
* Using `jenkins-button` class rather than YUI button
**Before**
**After**
* Generating code works as before

Refine interface of Pipeline Syntax

---

plugin/pom.xml
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/handle-prototype.js
pom.xml

Now that Prototype.js has been removed in 2.426.x, we can remove the no-longer needed `Object.toJSON` workaround.
`mvn clean verify -DskipTests`

Update to 2.426.x, simplify JSON parsing

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

Long implemented as https://github.com/jenkinsci/pipeline-plugin/commit/a2524aee0821acd8af138190fb27724ef1b0500e but apparently never before explicitly demonstrated in a test. Not likely to regress, but people sometimes ask how to extract `EnvAction.overriddenEnvironment` from an HTTP request.

Assert `@Exported` form of `EnvActionImpl`

---

.github/workflows/jenkins-security-scan.yml
dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Driver.java
lib/pom.xml

Experimental workaround based on the stack trace observed in https://github.com/jenkinsci/workflow-cps-plugin/pull/901. Undoes https://github.com/jenkinsci/workflow-cps-plugin/pull/915.

Enable Jenkins Security Scan and bypass CodeQL's JavaCompiler to support JDK 17+

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java

Seems to fix a problem I had originally tried to solve with #923 but misclassified. Similar in spirit to #368 and more directly to https://github.com/jenkinsci/workflow-cps-plugin/pull/367#discussion_r458869636 before that was reverted. Did not try to modify `isLaunched()`; it is not clear under which conditions we would care. Open to other suggestions.

Clear `CpsBodyExecution.thread`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java

Amending #925. Test case is in https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/738; did not manage to reproduce without Declarative (something weird in `ModelInterpreter.getParallelStages`). https://github.com/jenkinsci/workflow-cps-plugin/blob/3761c26d756586b2c88d3c9bbcf8ea577902129b/plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java#L151 is immediately responsible:
```
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:151)
at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:138)
at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyEx …
```

[JENKINS-73726] Avoid NPE trying to cancel a block which is already done

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

I ran into two unexpected NPEs in `CpsFlowExecution.cleanUpGlobalClassValue`. I have never seen them before, and I am not sure exactly what caused them. The user in question had a very complicated Pipeline library and a very active controller, which might be relevant. In both cases, I think we just want to ignore the unexpected `null`s and continue to attempt to clean up all other values. Here are the stack traces:
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
at java.base/java.lang.reflect.Field.get(Field.java:425)
at …
```

Prevent NPEs in `CpsFlowExecution.cleanUpGlobalClassValue` to make Pipeline cleanup more robust

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java

Trying to fix
```
Found one Java-level deadlock:
=============================
"Handling GET /…/job/main/ from … : Jetty (winstone)-17 Job/index.jelly WorkflowJob/sidepanel.jelly HistoryWidget/index.jelly":
waiting to lock monitor 0x00007f2714a7b680 (object 0x0000000672800000, a org.jenkinsci.plugins.workflow.cps.CpsFlowExecution),
which is held by "jenkins.util.Timer [#5]"
"jenkins.util.Timer [#5]":
waiting to lock monitor 0x00007f26a0200300 (object 0x00000006728000a0, a java.lang.Object),
which is held by "Handling GET /…/job/main/ from … : Jetty (winstone)-17 Job/index.jelly WorkflowJob/sidepanel.jelly HistoryWidget/index.jelly"
Java stack information for the threads listed above:
===================================================
"Handling GET /…/job/main/ from … : Jetty …
```

Avoid holding locks from `croak` when calling `notifyListeners`

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Introduced in #797, and seems to flake a lot, e.g.: https://github.com/jenkinsci/workflow-cps-plugin/runs/31557729869
Reproducible using
```diff
diff --git plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
index 51518e6f..519e1f14 100644
--- plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
+++ plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
@@ -652,6 +652,11 @@ public final class CpsThreadGroup implements Serializable {
}
void shutdown() {
+        try {
+            Thread.sleep(1000);
+        } catch (InterruptedException x) {
+            x.printStackTrace();
+        }
runner.shutdown();
}
```

`CpsFlowExecutionTest.iterateAfterSuspend` flaky

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java

[JENKINS-73941 - Option to hide "Use Groovy Sandbox" for users without Administer permission globally in the system](https://issues.jenkins.io/browse/JENKINS-73941)
Complements https://github.com/jenkinsci/workflow-cps-plugin/pull/948
In https://github.com/jenkinsci/script-security-plugin/pull/586, some additional shared methods have been included to better manage the shared logics related to the ForceSandbox functionality. We are including such methods to the current plugin logic.
This PR does not include any new functionality, but decrease the techDebt maintaining both, Script-Security and Workflow-CPS Plugin.
**No new tests are required.**
Tests implemented in https://github.com/jenkinsci/workflow-cps-plugin/pull/948 are already covering the new Scipt-Security logic.
The tests for the …

JENKINS-73941 - ForceSandbox - Unify logic in Script-Security for reducing techDeb

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/PauseUnpauseAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/RunningFlowAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/RunningFlowActions.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/RunningFlowActionsTest.java

[JENKINS-73984](https://issues.jenkins.io/browse/JENKINS-73984) Add a parent abstract Action and tie the factory to this type of action to avoid un-necessary consultation from `Actionable#getAction[s]`.
* Run a pipeline with Input step
* Verify that the Pause Action is displayed
* Verify that the Thread Dump Action is displayed

[JENKINS-74884] Tie RunningFlowActions factory to a specific type of action

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

The one source code change needed to allow use of a 5.x parent and 2.479.x baseline.

Allow `SnippetizerTester` to compile against new cores

---

plugin/pom.xml
pom.xml

PCT on Docker-enabled hosts failed after https://github.com/jenkinsci/jenkins/pull/9958 due to https://github.com/jenkinsci/workflow-cps-plugin/blob/5198556e9cead606cba728340bb6be96365a10e6/plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/SerialFormTest.java#L87 missing a dep. Also bumped baseline/BOM to pick up https://github.com/jenkinsci/support-core-plugin/pull/545 (fixing some warnings in the log) and to clean up after #952.

Adapt `SerialFormTest` to removal of `commons-compress`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/StepListenerTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsStepContextTest.java

Previously, the unexport of a step's body would only happen when scheduling the next execution (async mode).  If the step was not run async (due to having an outcome set prior to the step starting), the body was not removed until the CpsThreadGroup was finishing.  At this point the body's presence was treated as a resource leak and logged a warning.  Doing an explicit unexport for the sync case at the proper time eliminates the warnings from the fall-back cleanup.
Potential fix for https://issues.jenkins.io/browse/JENKINS-75067
I'm not sure if this solution is "correct", but it logically makes sense and all existing tests continue to pass.  Even if the proper fix is different (and/or best handled by you folks), I figured this PR could still prove valuable by providing a test case.
I …

[JENKINS-75067] Unexport step bodies when completed in synchronous mode

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayFlowFactoryAction.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/Workflow2Test.java

In CBCI HA scenarios, the `Queue.Item` (and its actions) can be rescheduled in another Jenkins replica. In such case it is required to persist the `sandbox` field, otherwise the reschedule will run without sandbox.
In a regular OSS Jenkins, you can hit the problem is you disable concurrent build execution and arrange for a build to be queued, then restart the controller, as demonstrated in the provided test.
Tested in CBCI HA context.

Persist `ReplayFlowFactoryAction#sandbox`

---

plugin/pom.xml
plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

[CloudBees-internal issue](https://cloudbees.atlassian.net/browse/BEE-55704)

`WorkflowTest.env` failure

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayPipelineCommandTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java

Following up #925: not only avoiding the symptom, but warning about the mistake. (Though not from `@NonCPS` methods.)
Note that this uses a distinct logging system from either #211 or #280, since in this case at the point at which the warning is printed we have easy access to a `TaskListener` (though `PropertyAccessBlock` would have additional access to a `SourceLocation` which may be helpful).

Warn user when forgetting `def` on a variable

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/Workflow2Test.java

Amending #968. https://github.com/jenkinsci/bom/pull/4622#issuecomment-2694978606
```
java.lang.NullPointerException: Cannot invoke "org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.isSandbox()" because the return value of "org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution()" is null
at org.jenkinsci.plugins.workflow.Workflow2Test.stage2(Workflow2Test.java:91)
```
Not reproduced locally—speculative.

Flake in `Workflow2Test`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java

A user comment in [JENKINS-75361](https://issues.jenkins.io/browse/JENKINS-75361) that has since been edited away, but is replicated in [my comment](https://issues.jenkins.io/browse/JENKINS-75361?focusedId=452863&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-452863) mentioned that #994 causes false positives for a relatively common pattern where assignments in closures are used as a DSL for building a map.
This PR adjusts the logic from that PR to consider `Closure.resolveStrategy` to try to reduce false positives a bit.
See new automated test.

[JENKINS-75361] Consider `Closure.resolveStrategy` to reduce false positives

---

plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly

This should address https://issues.jenkins.io/browse/JENKINS-75447
There is no longer a `getItem()` that accepts a plain `StaplerRequest`.  In #972 the signature was changed to accept a `StaplerRequest2`.  Rather than maintain two variants, [it was preferred](https://issues.jenkins.io/browse/JENKINS-75447?focusedId=453247&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-453247) to modify the jelly to use the  new signature.
There are no additional automated tests; there were no existing tests around this and there wasn't much precedence for tests specific to the EE migration.
This was manually validated via running in a debugger (against Jenkins 2.502), but also with the same setup from ticket's reproduction:
```Dockerfile
FROM jenkins/jenkins:2.487
RUN echo …
```

[JENKINS-75447] Fix Snippetizer rendering of "properties" step

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java

https://issues.jenkins.io/browse/JENKINS-75445 amending #994. Do not know much about this mode but it looks frightening! If you find the need for it, better switch to Scripted.
To reproduce,
```bash
mvnd -pl pipeline-model-definition test -Dtest=BasicModelDefTest#stages300
```
after
```diff
diff --git pom.xml pom.xml
index 2a014654..00f4c26d 100644
--- pom.xml
+++ pom.xml
@@ -75,7 +75,7 @@
<dependency>
<groupId>io.jenkins.tools.bom</groupId>
<artifactId>bom-${jenkins.baseline}.x</artifactId>
-        <version>4228.v0a_71308d905b_</version>
+        <version>4440.v39a_9eb_b_c6b_4d</version>
<scope>import</scope>
<type>pom</type>
</dependency>
```
Reproduced fix with:
```diff
diff --git pom.xml pom.xml
index 2a014654..a6628e01 100644
--- pom.xml
+++ pom.xml
@@ -75,10 +75,15 @@
<dependency> …
```

Ignore `__model__*` variables generated by Declarative in script splitting mode

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodySubContext.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java

@gbhat618 observed this error from code added recently in 5406e29e3c90829fd2981a6ed9077f4827220ba6 in a Pipeline which failed to stop after a hard kill. I will try to reproduce this case in a test.
```
java.lang.NullPointerException: Cannot invoke "org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(java.lang.Class, org.jenkinsci.plugins.workflow.cps.ContextVariableSet$ThrowingSupplier, org.jenkinsci.plugins.workflow.cps.ContextVariableSet$ThrowingSupplier)" because the return value of "org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariables()" is null
at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.handleError(CpsBodyExecution.java:378)
at PluginClassLoader for …
```

Prevent `NullPointerException` in `CpsBodyExecution.FailureAdapter`

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java

Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3. This library wasn't used very much in this plugin (mostly in tests), so in `src/main` I simply rewrote usages to use standard Java Platform functionality.

Migrate from Commons Lang 2 to Commons Lang 3

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

I am not sure exactly what this was for—it dates to https://github.com/jenkinsci/pipeline-plugin/commit/dc6631192748eaa0534e2145b1fd7eafdd14ffe5 during the prototype days—but I noticed it adding overhead to a bunch of threads in an overloaded controller ([CloudBees-internal reference](https://cloudbees.atlassian.net/browse/BEE-61521)):
```
java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.fillInStackTrace(java.base@21.0.8/Native Method)
at java.lang.Throwable.fillInStackTrace(java.base@21.0.8/Throwable.java:820)
- locked <0x00000000fff9ba58> (a java.lang.Exception)
at java.lang.Throwable.<init>(java.base@21.0.8/Throwable.java:258)
at java.lang.Exception.<init>(java.base@21.0.8/Exception.java:55)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4.<init>(CpsFlowExecution.java:100 …
```

Remove call stack from `runInCpsVmThread`

---

plugin/pom.xml
pom.xml

Configures the new properties from https://github.com/jenkinsci/maven-hpi-plugin/pull/771.
I updated the parent POM, added `<hpi.strictBundledArtifacts>true</hpi.strictBundledArtifacts>`, and confirmed that the build failed. I then added `<hpi.bundledArtifacts>diff4j,groovy-cps</hpi.bundledArtifacts>` and confirmed that the build passed.

Enable strict bundled artifact checks
