src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepEndNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/DynamicEnvironmentExpanderTest.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java

Downstream of #3. Fixes `load` step flow graph construction.
[the incremental change](https://github.com/jenkinsci/workflow-cps-plugin/pull/5/commits/934d37b7e5ca19d94d2d6190e7f242ec933441a3)

Load step flow graph fix

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/block.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

@rsandell found a problem with new HtmlUnit affecting `configRoundTrip` on `CpsFlowDefinition`. @tfennelly said he would take a look.
@reviewbybees

buildFormTree problem

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Implementation of https://github.com/jenkinsci/workflow-step-api-plugin/pull/2.

[JENKINS-26107] StepContext.hasBody implementation

---

src/test/java/org/jenkinsci/plugins/workflow/CpsFlowExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

As with
mvn -Djenkins.version=2.8 clean package
@reviewbybees esp. @kwhetstone

Fix some test failures on Jenkins 2

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Another symptom of [JENKINS-34281](https://issues.jenkins-ci.org/browse/JENKINS-34281).
Cf. https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/8, https://github.com/jenkinsci/workflow-api-plugin/pull/4, https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/4.
@reviewbybees

[JENKINS-34281] Lost FlowExecutionList entries

---

src/main/webapp/snippets/workflow.js

Missing colon in snippet

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly

Probably a regression in #12.
@reviewbybees esp. @stephenc

Pass `it` as an `Item`, not `Snippetizer`, to config forms

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java

[JENKINS-31840](https://issues.jenkins-ci.org/browse/JENKINS-31840)
Based on work by @christ66.
@reviewbybees

[JENKINS-31840] Adds a Support component for Pipeline build thread dumps

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/7 and https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/9 and https://github.com/jenkinsci/workflow-step-api-plugin/pull/4.
@reviewbybees

[JENKINS-31842] Thread dump improvements

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Follow-up to https://github.com/jenkinsci/pipeline-plugin/pull/193.
@reviewbybees

[JENKINS-29656] Assume Java 7 APIs

---

src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java

Extracted forRun helper method

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java

[JENKINS-36372](https://issues.jenkins-ci.org/browse/JENKINS-36372)

[JENKINS-36372] Root bindings not accessible to scripts loaded after restart

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java

[JENKINS-29922] Report symbols as well as steps in DSL error messages

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

Downstream of cloudbees/groovy-cps#38.

[JENKINS-34064] Pick up newer groovy-cps that reverts the JENKINS-26481 fix which only works in Jenkins 1

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Complements https://github.com/jenkinsci/workflow-job-plugin/pull/12. Makes problems like the test failure described in https://github.com/jenkinsci/pipeline-input-step-plugin/pull/2 more apparent. Also complements [JENKINS-26130](https://issues.jenkins-ci.org/browse/JENKINS-26130): in addition to messages explaining that resumption is blocked and why, print a message when it is unblocked.
@reviewbybees

Print a message whenever we are ready to resume running the program

---

src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java

This would be handy for testing - e.g., it'd simplify https://github.com/jenkinsci/workflow-multibranch-plugin/issues/28
cc @reviewbybees esp @jglick

Adding a helper method for testing doc generation.

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicData.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicDataWithSymbol.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListWithSymbolStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicWithSymbolStep.java

[JENKINS-29711](https://issues.jenkins-ci.org/browse/JENKINS-29711)
cc @reviewbybees esp @jglick @kohsuke @oleg-nenashev @svanoort

[FIXED JENKINS-29711] Handle monomorphic single-parameters to steps.

---

src/main/js/samples.js

Updated Maven sample

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsWhitelist.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
src/main/java/org/jenkinsci/plugins/workflow/cps/GlobalVariable.java
src/main/java/org/jenkinsci/plugins/workflow/cps/GlobalVariableSet.java
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/OriginalLoadedScripts.java
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayFlowFactoryAction.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly

Prerequisites of https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/10.
@reviewbybees

[JENKINS-31155] Infrastructure for shared libraries

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java

Noticed during `release:prepare` recently.
@reviewbybees

Trying to diagnose a flaky test

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java

Fixes a regression from #45.
@reviewbybees

[JENKINS-38167] NPE from scripts using @Field with instance initializers loading properties

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly

Downstream of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/16.
@reviewbybees

[JENKINS-33511] Doc update

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Improves display of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/18.
@reviewbybees

More polite display of routine resumption problems

---

src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

`ArrayList` iteration works, so might as well use that.
@reviewbybees

Simpler workaround for map iteration JENKINS-27421

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly

Forgotten in #60.
@reviewbybees

[JENKINS-29952] Updated documentation

---

src/main/java/org/jenkinsci/plugins/workflow/cps/ParamsVariable.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/ParamsVariable/help.jelly

[JENKINS-35698](https://issues.jenkins-ci.org/browse/JENKINS-35698)
@reviewbybees esp. @abayer

[JENKINS-35698] Make params offer default parameter values from the current definition as a fallback

---

src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java

[JDK-8075793](https://bugs.openjdk.java.net/browse/JDK-8075793)
@reviewbybees

Placate the JDK 9 compiler

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy

Prerequisite for https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/25. Otherwise you get a list of all extension points in Jenkins.
@reviewbybees

[JENKINS-28385] Gracefully handle Describable attributes of type Object

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/12.
@reviewbybees

[JENKINS-39275] Extend time limit to virtual thread dump

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly

Replacing occurrences of "groovy" with "Pipeline Script"
@reviewbybees

Update Snippet Generator

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

More memory leaks

---

src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadTest.java

Cf. https://github.com/jenkinsci/script-security-plugin/pull/96.
@reviewbybees

Test fixes

---

.mvn_exec_node
package.json
pom.xml

node/npm changes to allow use of parent pom v 2.17
Attn @jglick

[JENKINS-39154] Enable plugin parent pom 2.17

---

pom.xml

[Changes](https://github.com/cloudbees/groovy-cps/compare/groovy-cps-1.10...groovy-cps-1.11)

groovy-cps 1.11

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

[JENKINS-29656](https://issues.jenkins-ci.org/browse/JENKINS-29656)
Intended to replace #94.
@reviewbybees

[JENKINS-29656] Better handle failure renaming program.dat

---

pom.xml

Incorporates https://github.com/cloudbees/groovy-cps/pull/45 & https://github.com/cloudbees/groovy-cps/pull/46.
@reviewbybees

groovy-cps 1.12

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadTest.java

Fixing a flaky test

---

src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java

Pairs with https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/35.
@reviewbybees

Moving testRetry to workflow-basic-steps

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java

Ensure CpsVmExecutorService.reportProblem causes the build to end promptly

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

[JENKINS-41945](https://issues.jenkins-ci.org/browse/JENKINS-41945)
Apparent race condition involving garbage collection timing in Groovy 2.x (thus Jenkins 2.x). `ManagedLinkedList.Iter.next` is in fact documented to return null sometimes (unlike, say, `WeakHashMap.KeyIterator.next`), so we need to be prepared for that.
@reviewbybees

[JENKINS-41945] Ignore null elements in ClassInfo.globalClassSet.items

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

iotaStr incorrectly skipped every other number after around 500

---

src/main/java/org/jenkinsci/plugins/workflow/cps/ParamsVariable.java
src/test/java/org/jenkinsci/plugins/workflow/cps/ParamsVariableTest.java

[JENKINS-42367](https://issues.jenkins-ci.org/browse/JENKINS-42367)
@reviewbybees

[JENKINS-42367] Missing null check

---

Jenkinsfile
pom.xml

Downstream of https://github.com/jenkinsci/plugin-pom/pull/50. Reverts part of https://github.com/jenkinsci/pipeline-plugin/pull/290 (not the actual fix AFAICT). Trying to diagnose cryptic random failures like [this one](https://gist.github.com/jglick/481009295c265d37b1592c68a6913adf#file-console-txt-L4746-L4786), and to see if I can get the Windows build to succeed amending #110.
@reviewbybees esp. @tfennelly & @ydubreuil

Trying to get npm to work more consistently

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

[JENKINS-26137](https://issues.jenkins-ci.org/browse/JENKINS-26137?focusedCommentId=275544&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-275544)
Trying to solve an apparent race condition frequently affecting tests.
Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/35.
@reviewbybees

[JENKINS-26137] Pass pickleFactories directly into the RiverWriter constructor

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

[JENKINS-43361](https://issues.jenkins-ci.org/browse/JENKINS-43361)
@reviewbybees

[JENKINS-43361] Unreproducible NPE

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java

[JENKINS-43019](https://issues.jenkins-ci.org/browse/JENKINS-43019)
You just do not want to know.
@reviewbybees

[JENKINS-43019] Suppressing GroovyClassLoader.InnerLoader fixes stuff

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Demonstrating that ConfigSlurper can lead to memory leaks but evaluate does not

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

[JENKINS-43055](https://issues.jenkins-ci.org/browse/JENKINS-43055)
Was necessary to pinpoint the culprit.
@reviewbybees

[JENKINS-43055] Improve diagnostics to include a stack trace

---

src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/California.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListWithSymbolStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicWithSymbolStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/Nevada.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/NewYork.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/State.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/StateMetaStep.java

Amends #123: I was afraid I had missed a case involving symbols, but it turns out the original fix works. Came up in the context of #98.
@reviewbybees

Extra test for JENKINS-43934

---

pom.xml

Subsumes #128 to pick up https://github.com/jenkinsci/plugin-pom/pull/63 and thus avoid downloading from external servers at all.
@reviewbybees esp. @cliffmeyers

Yarn with caching

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/38

Add support for GraphListener as ExtensionPoint

---

pom.xml

See https://github.com/jenkinsci/jenkins-test-harness/pull/35 for background.
@reviewbybees

Picking up a newer version of git so as to avoid a noisy linkage error

---

pom.xml

[JENKINS-44578](https://issues.jenkins-ci.org/browse/JENKINS-44578)
Simply picks up https://github.com/cloudbees/groovy-cps/pull/59.
@reviewbybees

[JENKINS-44578] Use native CpsTransformer

---

src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java

Because `StepDescriptor.all` was empty. Error:
No such DSL method 'semaphore' found among steps [] or symbols […OK…] or globals […OK…]
Initially I thought the problem was that `functions` (intrduced in https://github.com/jenkinsci/pipeline-plugin/commit/62ab58d2e0894f160475ac1592e841adb9f2468b) was being cached with an empty list during a call at a bad time, and later a legitimate call then picked up the bad cache. But in fact it seems that sometimes the method is called when the extension list is just empty, and shortly thereafter it is OK. Not really sure what is going on here but I suspect this is specific to `RestartableJenkinsRule`: I do see two sets of Jenkins startup log messages, which looks anomalous, and suggests that `ItemListener.onLoaded` fires in between and things explode. …

WaitForConditionStepTest#restartDuringDelay sometimes flaked

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java

[JENKINS-38268](https://issues.jenkins-ci.org/browse/JENKINS-38268)
Downstream of https://github.com/cloudbees/groovy-cps/pull/61

[JENKINS-38268] Testing for lexical closure scope

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Observed a problem in the field possibly correlated with
```
java.lang.Error: java.lang.reflect.InvocationTargetException
at …
at jenkins.model.Jenkins._cleanUpRunTerminators(Jenkins.java:3284)
at jenkins.model.Jenkins.cleanUp(Jenkins.java:3206)
at hudson.lifecycle.UnixLifecycle.restart(UnixLifecycle.java:73)
at jenkins.model.Jenkins$25.run(Jenkins.java:4159)
Caused by: java.lang.reflect.InvocationTargetException
at …
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:259)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:91)
at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$8.call(CpsFlowExecution.java:1207)
at …
```

Do not allow exceptions from suspendAll to cancel shutdown

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsWhitelist.java
src/test/java/org/jenkinsci/plugins/workflow/CpsDefaultGroovyMethodsTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

Downstream of https://github.com/jenkinsci/script-security-plugin/pull/124, post https://github.com/jenkinsci/workflow-cps-plugin/pull/124.
Notes that `sum` doesn't work due to needing `invokeMethod`, which is...obviously a non-starter.

Tests for DGM running through script security in actual jobs.

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepEndNode.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java

[JENKINS-45109](https://issues.jenkins-ci.org/browse/JENKINS-45109)
@reviewbybees

[JENKINS-45109] Making StepNode.typeFunctionName honor metasteps

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/44.
@reviewbybees

[JENKINS-31582] Using ArgumentsAction.getResolvedArguments to better handle JENKINS-45109

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly

[JENKINS-26100](https://issues.jenkins-ci.org/browse/JENKINS-26100)
@reviewbybees

[JENKINS-26100] Updating documentation

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

Make it more obvious where the @script checkout is happening

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-42563](https://issues.jenkins-ci.org/browse/JENKINS-42563)
Downstream of https://github.com/jenkinsci/script-security-plugin/pull/133.
@reviewbybees

[JENKINS-42563] Demonstrate that super calls run through the sandbox interceptor

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-34599](https://issues.jenkins-ci.org/browse/JENKINS-34599) & [JENKINS-45629](https://issues.jenkins-ci.org/browse/JENKINS-45629)
Downstream of https://github.com/jenkinsci/script-security-plugin/pull/132.
@reviewbybees

[JENKINS-34599] [JENKINS-45629] Demonstrating fixes

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

Deleting some obsolete Groovy 1.x code

---

src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
src/test/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHackTest.java

[JENKINS-34645](https://issues.jenkins-ci.org/browse/JENKINS-34645)
@reviewbybees

[JENKINS-34645] Serializable array iterator

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-46088](https://issues.jenkins-ci.org/browse/JENKINS-46088)
Downstream of https://github.com/jenkinsci/groovy-sandbox/pull/37,
https://github.com/cloudbees/groovy-cps/pull/69, and
https://github.com/jenkinsci/script-security-plugin/pull/139

[JENKINS-46088] Downstream testing of double-transformation fix

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/CpsStringGroovyMethodsTest.java

[JENKINS-46358](https://issues.jenkins-ci.org/browse/JENKINS-46358)
Downstream of https://github.com/cloudbees/groovy-cps/pull/70 and
https://github.com/jenkinsci/script-security-plugin/pull/145

[JENKINS-46358] Tests for StringGroovyMethods transformations

---

Jenkinsfile
pom.xml

[JENKINS-33358](https://issues.jenkins-ci.org/browse/JENKINS-33358)
@reviewbybees

[JENKINS-33358] Test against 2.73.x since that includes Groovy 2.4.11

---

src/main/java/org/jenkinsci/plugins/workflow/cps/RunningFlowActions.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

I happened to notice that even anonymous users were offered a **Pause/Resume** sidebar link on running builds; clicking the link shows a **Done.** tooltip but has no other effect.
@reviewbybees

Do not even offer PauseUnpauseAction unless you actually have CANCEL

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-47064](https://issues.jenkins-ci.org/browse/JENKINS-47071)
Also bumps parent POM for Intellij.
Downstream of https://github.com/cloudbees/groovy-cps/pull/75

[JENKINS-47064] Verify fix for BooleanClosureWrapper

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/DynamicEnvironmentExpanderTest.java
src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
src/test/java/org/jenkinsci/plugins/workflow/SubtypeInjectingStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/CurveMetaStep.java
src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/EchoResultStep.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/30.
@reviewbybees

[JENKINS-26148] Using default implementation of StepExecution.stop

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionMemoryTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

[JENKINS-47105](https://issues.jenkins-ci.org/browse/JENKINS-47105)
@reviewbybees

[JENKINS-47105] Fixing test failure in loaderReleased

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

[JENKINS-44619](https://issues.jenkins-ci.org/browse/JENKINS-44619)

[FIXED JENKINS-44619] Don't allow replays of nonbuildable jobs

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

Buglet I just noticed.
@reviewbybees

CpsScmFlowDefinition should add a WorkspaceActionImpl corresponding t…o the directory it actually acquired

---

src/main/java/org/jenkinsci/plugins/workflow/cps/GlobalVariable.java

After https://github.com/jenkinsci/docker-workflow-plugin/pull/127, another attempt to steer the innocent away from a commonly abused API.
@reviewbybees

Warning about misuse of this extension point

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-48501](https://issues.jenkins-ci.org/browse/JENKINS-48501)
Downstream of https://github.com/jenkinsci/script-security-plugin/pull/173

[JENKINS-48501] Test verifying fix for variable declaration

---

pom.xml

Integration test for https://github.com/cloudbees/groovy-cps/pull/80 + https://github.com/cloudbees/groovy-cps/pull/79.
@reviewbybees

Pick up recent groovy-cps fixes

---

pom.xml
src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

[JENKINS-37215](https://issues.jenkins-ci.org/browse/JENKINS-37215)
Downstream of https://github.com/jenkinsci/structs-plugin/pull/35. Mirrors https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/14.
@reviewbybees

[JENKINS-37215] Symbol support

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

Replaces #160, #161, #162 
Rollup of test verifications for a number of issues:
* [JENKINS-38052](https://issues.jenkins-ci.org/browse/JENKINS-38052)
* [JENKINS-27916](https://issues.jenkins-ci.org/browse/JENKINS-27916) (sorta)
* [JENKINS-41248](https://issues.jenkins-ci.org/browse/JENKINS-38052)
* [JENKINS-28321](https://issues.jenkins-ci.org/browse/JENKINS-28321)

Verify issues resolved before 2.39

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-45575](https://issues.jenkins-ci.org/browse/JENKINS-45575), [JENKINS-49679](https://issues.jenkins-ci.org/browse/JENKINS-49679)
Specifically https://github.com/cloudbees/groovy-cps/pull/81 and https://github.com/cloudbees/groovy-cps/pull/82

[JENKINS-45575, JENKINS-49679] Test multiple assignment CPS fixes

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-45982](https://issues.jenkins-ci.org/browse/JENKINS-45982)

[JENKINS-45982] Fix calling CPS-transformed super methods.

---

src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java

[JENKINS-33614](https://issues.jenkins-ci.org/browse/JENKINS-33614)
I don't *love* this, so feel free to critique/veto.

[FIXED JENKINS-33614] Add link to script approval when a rejection occurs

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java

[JENKINS-50171](https://issues.jenkins-ci.org/browse/JENKINS-50171)
It just makes things go badly.

[FIXED JENKINS-50171] Don't use package names in loadedScripts keys.

---

src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java

[JENKINS-50407](https://issues.jenkins-ci.org/browse/JENKINS-50407)
@reviewbybees

[JENKINS-50407] Trying to diagnose an NPE

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java

[JENKINS-42836](https://issues.jenkins-ci.org/browse/JENKINS-42836)

[FIXED JENKINS-42836] env expand the script path from SCM.

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayPipelineCommand.java
src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly
src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

Fixes [JENKINS-50784](https://issues.jenkins-ci.org/browse/JENKINS-50784) in conjunction with https://github.com/jenkinsci/workflow-job-plugin/pull/95.
See comments on the JIRA for explanation in detail - note that this is more or less what @jglick suggested.

Lazy load fix to get or null [JENKINS-50784]

---

.mvn/extensions.xml
.mvn/maven.config
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java

Extracted from #229, since I also expect to need incremental versions.

Incrementalified

---

pom.xml

[JENKINS-53240](https://issues.jenkins-ci.org/browse/JENKINS-53420)
See https://github.com/jenkinsci/script-security-plugin/pull/223

[JENKINS-53240] Verify fix for script-security issue

---

.mvn/extensions.xml
pom.xml

As in the title, I am most interested in the changes in [plugin:3.18](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md#318), but I went ahead and updated the parent to the latest version.
@reviewbybees

Update parent for auto-reincrementalification after releases

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

Picks up https://github.com/jenkinsci/jenkins-test-harness/pull/108 via https://github.com/jenkinsci/plugin-pom/pull/123.

Using MockAuthorizationStrategy

---

pom.xml

See https://github.com/jenkinsci/structs-plugin/pull/38

Pick up structs change to coerce strings to numbers/boolean

---

README.md

To help people find this plugin, mention "WorkflowScript", "Jenkinsfile" and "workflow-cps"

Mention workflow-cps name in README

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/38.

[JENKINS-49337] GeneralNonBlockingStepExecution

---

src/main/js/samples.js

So that https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/82 does not even show up!

archive → archiveArtifacts in sample

---

pom.xml

Merely integates https://github.com/cloudbees/groovy-cps/pull/97.

Pick up JENKINS-57085 fix

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

Downstream of https://github.com/jenkinsci/workflow-support-plugin/pull/94.
Bound to fail until upstream build completes; currently stuck waiting for a Windows executor, sigh.

Use DefaultStepContext simplification

---

src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

[JENKINS-54186](https://issues.jenkins-ci.org/browse/JENKINS-54186). Also see https://github.com/jenkinsci/git-plugin/pull/709.

[JENKINS-54186] ArgumentsActionImpl robustness against weird Describable

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

[JENKINS-50223](https://issues.jenkins-ci.org/browse/JENKINS-50223)

[JENKINS-50223] Memory leaks related to libraries

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/GraphListenerTest.java

Complements https://github.com/jenkinsci/workflow-api-plugin/pull/93 and amends #266.

Catch Error from GraphListener

---

Jenkinsfile
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

@jenkinsci/java11-support 
Let's see what happens.

Add Java 11 build

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadTest.java

Downstream of https://github.com/jenkinsci/workflow-job-plugin/pull/131.

[JENKINS-46076] Flake in CpsThreadTest.stop

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

I am migrating these tests to pipeline-build-step via https://github.com/jenkinsci/pipeline-build-step-plugin/pull/27.

Remove tests for BuildTriggerStep

---

src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/gdsl.groovy

See [JENKINS-30572](https://issues.jenkins-ci.org/browse/JENKINS-30572).
Fixes syntax highlighting for `parallel` when using `gdsl.groovy` with IntelliJ (tested manually). Does not change the fact that the snippet generator throws an exception for `parallel` or that doc generation for `parallel` fails [here](https://jenkins.io/doc/pipeline/steps/workflow-cps/). Also fixes the GDSL for parameters of type `List`, which were being reported as type `Map`.
I did some experimentation, and you can get rid of the special-casing in gdsl.groovy, get the snippet generator to return an empty step rather than throwing an error, and make doc generation work correctly by adding `@DataBoundConstructor` to `ParallelStep`'s constructor, adding public getters for `closures` and `failFast`, and then using …

[JENKINS-30572] Support ParallelStep in gdsl.groovy and fix parameter types for some steps

---

src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

Reduces test time from ~26s → ~15s for me.

Speed up ArgumentsActionImplTest using @ClassRule

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
src/test/java/org/jenkinsci/plugins/workflow/StepListenerTest.java

[JENKINS-58084](https://issues.jenkins-ci.org/browse/JENKINS-58084)
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/96

[JENKINS-58084] Call StepListeners before executing steps

---

src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

Simplify a couple test asserts

Simplify test asserts

---

src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepTest.java

Similar to #320 and #308. Actually the savings seem to be somewhat marginal, I guess because Jenkins startup is mostly about class loading, and within a single JVM tests using flat-classpath mode do not need to do fresh class loading. Still, it is something.

Using ClassRule in some more places

---

src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

Made it a bit faster, and made it probably more legible than when using `ErrorCollector`.
#315 & #316 will need to be merged with this.

Rewrote CpsVmExecutorServiceTest to use ClassRule

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java

[JENKINS-59425](https://issues.jenkins-ci.org/browse/JENKINS-59425)

[JENKINS-59425] Fail with a sensible error message when the script is missing from scm

---

CHANGELOG.md

I am planning on releasing this later today, so I want to go ahead and update the changelog.

Update changelog for 2.75 release

---

CHANGELOG.md

I am planning on releasing this plugin later today.

Update changelog for 2.76 release

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java

Class design improvement that removes static initialization block as well ass changes static field naming to follow Java naming conventions

Remove static initialization block

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsWhitelist.java
src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyClassLoaderWhitelist.java

Complements https://github.com/jenkinsci/script-security-plugin/pull/279.

Diagnostics & robustness for Pipeline-specific Whitelist implementations

---

pom.xml

Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/47.

Pick up DynamicContext as nonbeta

---

CHANGELOG.md

I would like to release the plugin today.

Add 2.78 release notes

---

src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySample.java
src/main/js/samples.js
src/main/js/workflow-editor.js
src/main/resources/org/jenkinsci/plugins/workflow/cps/samples/github-maven.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/samples/hello.groovy
src/main/resources/org/jenkinsci/plugins/workflow/cps/samples/scripted.groovy
src/main/resources/org/jenkinsci/plugins/workflow/editor/workflow-editor.jelly

Plan to introduce something in the `kubernetes` plugin. Also at some point the Declarative-specific samples should be moved out.

Introduced GroovySample extension point

---

CHANGELOG.md

I am planning on releasing the plugin today.

Add release notes for 2.81

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

See [JENKINS-46961](https://issues.jenkins-ci.org/browse/JENKINS-46961) and https://github.com/jenkinsci/workflow-job-plugin/pull/167.
In most cases, I think that https://github.com/jenkinsci/workflow-job-plugin/pull/167 alone is enough to fix JENKINS-46961, because if the thread is interrupted an exception will be thrown in `CpsFlowExecution.start` either by `CpsFlowExecution.parseScript` or `FlowHead.newStartNode`. 
However, in some cases I have seen an `InterruptedException` be swallowed (for example by Git Client plugin in [this try/catch block](https://github.com/jenkinsci/git-client-plugin/blob/ecbbd8b5decea6efc33b637fa22139d479d9c21b/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L346-L351) while checking out out a Pipeline library loaded via the `@Library` …

[JENKINS-46961] Prevent Pipeline builds from resuming after being aborted while starting

---

CHANGELOG.md

I am planning on releasing the plugin today.

Add release notes for 2.83

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java

Inspired by https://github.com/jenkinsci/jenkinsfile-runner/pull/364.

If resume is blocked on a build, there is no purpose in ever saving program.dat

---

.mvn/extensions.xml
Jenkinsfile
pom.xml

PCT compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

Update parent POM

---

CHANGELOG.md

I am planning on releasing the plugin today.

Add release notes for 2.84

---

CHANGELOG.md

Planning to release plugin after #399 gets merged

prepare for 2.86 release

---

CHANGELOG.md

Planning to do a release today

update changelog for 2.87

---

pom.xml

Fix build on mac m1

---

CHANGELOG.md

add 2.90 to changelog

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
CHANGELOG.md

Enable release drafter github action

Enable release drafter

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java

Prevents https://github.com/jenkinsci/credentials-binding-plugin/pull/143 from breaking a few tests. Noticed in https://github.com/jenkinsci/bom/pull/573.

Adapt to fix in `BindingStep`

---

Jenkinsfile

https://github.com/jenkinsci/workflow-cps-plugin/pull/474/checks?check_run_id=4099320483 for example.

`Jenkinsfile` cleanups

---

Jenkinsfile

This version number is unlikely to be maintained.

Remove version from `Jenkinsfile`

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java

Remove usage of `ImmutableMap`

Ensure compatibility with Guava 31+

---

src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java

Continues along the lines of #487 by migrating from `com.google.common.util.concurrent.SettableFuture` to `java.util.concurrent.CompletableFuture` wherever compatibility is not a concern (i.e., local variables and private transient fields).

Reduce usages of Guava

---

README.md

remove badges from readme

---

.gitignore

Eg. `yarn-error.log` may be created as part of the build.
----------------------------------------

Add *.log to gitignore

---

.github/dependabot.yml
package.json
yarn.lock

Supersedes a bunch of open DB PRs. Did a manual sanity check that the Pipeline editor works.

Update some JS deps

---

pom.xml

A release of this would help us do Java 17 testing of this plugin in BOM. CC @car-roll

Update plugin parent POM and BOM

---

pom.xml

BOM updates

---

README.md

Add missing `}` to example

---

package.json
pom.xml
yarn.lock

Misc frontend updates, does dependabot take a nap? I see no babel PRs 👀

Update webpack, babel, npm and node

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyClassLoaderWhitelist.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java

A few PRs were merged to the `master` branch after https://github.com/jenkinsci/workflow-cps-plugin/commit/1af77ffcc773ffac4eb49956168b9778dca9a3b6 had been staged, so we cannot push the security fix directly and need to merge it into `master` instead.
I am marking this as `internal` for now to avoid creating a CD release since the advisory has only just gone out and we do not want users to see another update right away.

[SECURITY-2824]

---

pom.xml

I'm going to file a PR that reorganizes the source code layout in this repo soon, so I am trying to clean up open PRs beforehand.
This replaces https://github.com/jenkinsci/workflow-cps-plugin/pull/602, #593 and #598.

Update plugin BOM and remove unnecessary version specifications in pom.xml

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/MethodPointerBlock.java
lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java

Fixes https://github.com/cloudbees/groovy-cps/issues/93.

Convert GStringImpl to String in the RHS of CPS-transformed method pointers

---

Jenkinsfile

Corresponding to the latest archetype.

Add Java 17 to build matrix

---

plugin/pom.xml
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java

…and not the actual behavior of the `stage` step when run as of https://github.com/jenkinsci/pipeline-stage-step-plugin/pull/94.

Adapt `DSLTest.legacyStage` to test only the special case

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/view/ThemeUtil.java
plugin/src/main/js/workflow-editor.js
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction/index.jelly
plugin/src/main/resources/org/jenkinsci/plugins/workflow/editor/workflow-editor.jelly

Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/127. Can be merged and released as-is without any regressions, but depends on https://github.com/jenkinsci/dark-theme-plugin/pull/319 for the fix to actually take effect. I tested this by running in both the dark and light theme and verifying that the background was adjusted appropriately.

Dark, but not Dark (System), theme support

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

https://github.com/jenkinsci/workflow-cps-plugin/pull/596#issuecomment-1280946767

Avoid logging a warning from `isComplete`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

https://github.com/jenkinsci/workflow-cps-plugin/pull/659#issuecomment-1471957378

[JENKINS-70808] Third attempt at lockless `Timing.close`

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java

Tried to capture noteworthy edits I could find in the forked code deleted in https://github.com/jenkinsci/workflow-job-plugin/pull/361.

Backports to `PersistenceProblemsTest` from `CpsPersistenceTest` edits

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java

Downstream of https://github.com/jenkinsci/support-core-plugin/pull/496.

Use `ComponentCategory.BUILDS`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java

See https://github.com/jenkinsci/pipeline-build-step-plugin/pull/128#discussion_r1427007989 and the next comment.
If `FlowExecution.saveActions` is called for a Pipeline with a completed execution, in some cases (all cases as of https://github.com/jenkinsci/workflow-cps-plugin/pull/807), the save will be a no-op and nothing will be written to disk. Notably this method is called implicitly when updating actions on a `FlowNode` or when explicitly calling `FlowNode.save`.
We should throw an error in this case instead to make it easier for developers to detect and identify any issues. Generally speaking, to persist metadata for a possibly-completed build, you should use an `Action` on the `Run` that stores `FlowNode.getId` as needed.
TODO:
```[tasklist]
```

Throw an exception when trying to save actions for a `FlowNode` for a completed execution

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist/default-allowlist

Reverts #538.
See https://github.com/jenkinsci/workflow-cps-plugin/pull/538#issuecomment-1883042255.
```[tasklist]
```

Revert "Merge pull request #538 from dwnusbaum/post-SECURITY-359"

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStep.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSetTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/CurveMetaStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListWithSymbolStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicWithSymbolStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/StateMetaStep.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/chemical/DetectionMetaStep.java

Cleanup after #830. Analogous to https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/103. Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/149.

Fix deprecations, avoid `@Inject`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

add workaround to remove multiplescms.MultiSCM support in pipeline

add workaround to remove multiplescms.MultiSCM support in pipeline

---

lib/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java

`mvn clean verify -DskipTests`

Stop using EOL JSR 305 annotation

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/IgnoredInternalClasses.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java

Amending #228. ([CloudBees-internal issue](https://cloudbees.atlassian.net/browse/BEE-40343))

False positives from `LoggingInvoker.isInternal`

---

plugin/pom.xml
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java

Analogous to https://github.com/jenkinsci/workflow-multibranch-plugin/pull/314.

Remove `subversion` test dep

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java

https://issues.jenkins.io/browse/JENKINS-73031?focusedId=449518&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-449518

[JENKINS-73031] Print hint that a `static` `interface` method may be to blame

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java

https://github.com/jenkinsci/workflow-cps-plugin/pull/994#discussion_r1975222014

[JENKINS-75353] Ignore `Closure` metaproperties

---

plugin/pom.xml
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java

Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/383.

Updated to `FlowExecution.getAuthentication2`

---

plugin/src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java

Very old test apparently dating to original Workflow prototype, not testing any realistic scenario that I can see. Timed out twice in a row in #1008 on Windows only https://github.com/jenkinsci/workflow-cps-plugin/pull/1008/checks?check_run_id=40279248176 where the thread dump does not show what the test is waiting for (maybe due to limitations in deprecated `RestartableJenkinsRule`, used from deprecated superclass `SingleJobTestBase`). Does not seem worth investigating and fixing.

Deleting `SerializationTest.persistEphemeralObject`

---

.github/dependabot.yml

Dependabot groups take 2

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

Not really sure how this happens, but I saw a thread dump during a slow shutdown (took several minutes) in which `CpsFlowExecution.suspendAll` was hung in `AbstractFuture$TrustedFuture.get` apparently waiting for `programPromise.get`, which does not make much sense since this should already be done if there is a valid build that actually needs suspension. [CloudBees-internal issue](https://cloudbees.atlassian.net/browse/BEE-57721)

`suspendAll` should not wait for `programPromise`

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

* withReadLock
* withWriteLock
I've been reviewing the lock flows for the existing implementation (without spotting any issue), but I thought it would be clearer this way.

Implement methods to interact with `TimingFlowNodeStorage` locks

---

plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

Complementing https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/470.

Improved logging in `CpsStepContext`
